import React from 'react';
import {createRoot} from 'react-dom/client';
import Page from '../app/page';
import {ErrorBoundary} from '../components/error-boundary';
import '../app/globals.css';
import '../app/theme.css';
import '../app/ambience.css';
import '../app/notes-polish.css';
import '../app/motion.css';
import '../app/interaction-polish.css';
import '../app/companion-polish.css';
import '../app/detail-six.css';
import '../app/settings-calendar.css';
if(window.LukeAndroid)document.documentElement.dataset.nativeLaunching='true';
createRoot(document.getElementById('root')!).render(<ErrorBoundary><Page/></ErrorBoundary>);
