'use client';
import {useEffect,useRef,useState,memo} from 'react';
import {ImagePlus,RotateCcw,Check} from 'lucide-react';
import {BUBBLES,COMPANIONS,DEFAULT_DISPLAY,prepareAvatar,type DisplayPreferences} from '@/lib/display-preferences';
import {useDisplayPreferences} from '@/hooks/use-display-preferences';
export const ChatAvatar=memo(function ChatAvatar({mine,preferences,name}:{mine:boolean;preferences:DisplayPreferences;name:string}){return <img className="chat-avatar" src={mine?preferences.avatar:COMPANIONS[preferences.lukeAvatar]} width="36" height="36" alt={mine?`${name}的头像`:'夏彦的头像'} loading="lazy" decoding="async" onError={event=>{if(event.currentTarget.dataset.fallback)return;event.currentTarget.dataset.fallback='true';event.currentTarget.src=mine?COMPANIONS.dog:COMPANIONS.cat;}}/>;});
export function FontSettings({chatOnly=false}:{chatOnly?:boolean}){
 const {preferences:p,update,error}=useDisplayPreferences();
 return <section className="preference-card font-controls" aria-label={chatOnly?'聊天字号':'文字大小'}><h3>{chatOnly?'聊天文字':'文字大小'}</h3>{!chatOnly&&<label>全局字号 <output>{Math.round(p.scale*100)}%</output><input aria-label="全局字号" type="range" min="85" max="130" step="5" value={Math.round(p.scale*100)} onChange={e=>update({scale:Number(e.target.value)/100})}/></label>}<label>聊天字号 <output>{p.chatSize} px</output><input aria-label="聊天字号" type="range" min="13" max="24" step="1" value={p.chatSize} onChange={e=>update({chatSize:Number(e.target.value)})}/></label><p className="font-sample">今天，也想听你说说身边的小事。</p><button type="button" className="text-button" onClick={()=>update(chatOnly?{chatSize:16}:{scale:1,chatSize:16})}><RotateCcw size={15}/>恢复默认字号</button>{error&&<p role="alert">{error}</p>}</section>;
}
export function ChatAppearance(){
 const {preferences:p,update,error}=useDisplayPreferences(),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),selection=useRef<AbortController|null>(null);
 useEffect(()=>()=>selection.current?.abort(),[]);
 async function choose(file:File){selection.current?.abort();const controller=new AbortController();selection.current=controller;setBusy(true);setNotice('');try{const avatar=await prepareAvatar(file,controller.signal);if(!controller.signal.aborted&&selection.current===controller)update({avatar});}catch(e){if(!controller.signal.aborted)setNotice(e instanceof Error?e.message:'头像处理失败。');}finally{if(selection.current===controller){setBusy(false);selection.current=null;}}}
 return <div className="settings-stack chat-appearance"><section className="preference-card"><h3>我的头像</h3><div className="avatar-personal"><ChatAvatar mine preferences={p} name="我"/><label className="avatar-upload"><ImagePlus size={17}/><span>{busy?'正在处理…':'选择图片'}</span><input type="file" accept="image/jpeg,image/png,image/webp" aria-label="选择我的头像" onChange={e=>{const f=e.currentTarget.files?.[0];e.currentTarget.value='';if(f)void choose(f);}}/></label><button type="button" className="text-button" onClick={()=>{selection.current?.abort();selection.current=null;setBusy(false);update({avatar:DEFAULT_DISPLAY.avatar});}}>恢复默认</button></div><div className="avatar-choices" aria-label="内置头像">{(Object.keys(COMPANIONS) as Array<keyof typeof COMPANIONS>).map((key,i)=><button type="button" key={key} aria-label={['小狗头像','蜂蜜吐司头像','猫耳头像'][i]} aria-pressed={p.avatar===COMPANIONS[key]} onClick={()=>{selection.current?.abort();selection.current=null;setBusy(false);update({avatar:COMPANIONS[key]});}}><img src={COMPANIONS[key]} alt="" width="48" height="48"/></button>)}</div></section><section className="preference-card"><h3>夏彦的头像</h3><div className="avatar-choices">{(['cat','toast'] as const).map(key=><button type="button" key={key} aria-label={key==='cat'?'夏彦猫耳头像':'夏彦吐司头像'} aria-pressed={p.lukeAvatar===key} onClick={()=>update({lukeAvatar:key})}><img src={COMPANIONS[key]} width="48" height="48" alt=""/></button>)}</div></section><section className="preference-card"><h3>聊天气泡</h3><div className="bubble-choices">{BUBBLES.map(b=><button type="button" key={b.id} aria-label={`气泡：${b.name}`} aria-pressed={p.bubble===b.id} onClick={()=>update({bubble:b.id})}>{b.image?<img src={b.image} alt="" width="280" height="150" loading="lazy"/>:<span className="bubble-plain-sample">把今天说给我听。</span>}<span className="bubble-choice-label">{b.name}{p.bubble===b.id&&<Check size={16}/>}</span></button>)}</div></section><FontSettings chatOnly/>{(notice||error)&&<p role="alert">{notice||error}</p>}</div>;
}
