'use client';
import {useEffect,useRef,useState} from 'react';
import {MapPin,PlugZap} from 'lucide-react';
import {complete,type ModelConfig} from '@/lib/model';
import {locate} from '@/lib/location';
import type {useConnections} from '@/components/connections';
type Connections=ReturnType<typeof useConnections>;
export function ModelSettings({connections}:{connections:Connections}){
 const [model,setModel]=useState(connections.model),[notice,setNotice]=useState(''),[testing,setTesting]=useState(false),[dirty,setDirty]=useState(false);const task=useRef<AbortController|null>(null);
 useEffect(()=>()=>task.current?.abort(),[]);
 function patch(value:Partial<ModelConfig>){setModel(m=>({...m,...value}));setDirty(true);}
 async function test(){task.current?.abort();const controller=new AbortController();task.current=controller;setTesting(true);setNotice('正在测试连接');try{await complete(model,[{role:'user',content:'请只回复：连接成功。'}],controller.signal,100);if(!controller.signal.aborted)setNotice('连接成功，保存后应用设置。');}catch(e){if(!controller.signal.aborted)setNotice(e instanceof Error?e.message:'连接失败');}finally{if(!controller.signal.aborted)setTesting(false);}}
 return <form className="settings-stack" onSubmit={e=>{e.preventDefault();try{connections.apply(model,connections.weather);setDirty(false);setNotice('模型设置已保存');}catch(e){setNotice(e instanceof Error?e.message:'设置未保存');}}}>
 <h3><PlugZap size={18}/> 对话连接</h3><label>接口地址<input type="url" required aria-label="模型接口地址" placeholder="https://服务地址/v1" value={model.baseUrl} onChange={e=>patch({baseUrl:e.target.value})}/></label><label>模型名称<input required maxLength={150} aria-label="模型名称" value={model.model} onChange={e=>patch({model:e.target.value})}/></label><label>API Key<input type="password" aria-label="模型密钥" autoComplete="off" value={model.key} onChange={e=>patch({key:e.target.value})}/></label>
 <details className="settings-advanced"><summary>备用模型</summary><div className="settings-stack"><label>备用接口地址<input type="url" value={model.fallback?.baseUrl??''} onChange={e=>patch({fallback:{...model.fallback,baseUrl:e.target.value,model:model.fallback?.model??'',key:model.fallback?.key??''}})}/></label><label>备用模型名称<input maxLength={150} value={model.fallback?.model??''} onChange={e=>patch({fallback:{...model.fallback,baseUrl:model.fallback?.baseUrl??'',model:e.target.value,key:model.fallback?.key??''}})}/></label><label>备用密钥<input type="password" autoComplete="off" value={model.fallback?.key??''} onChange={e=>patch({fallback:{...model.fallback,baseUrl:model.fallback?.baseUrl??'',model:model.fallback?.model??'',key:e.target.value}})}/></label><button type="button" className="text-button" onClick={()=>patch({fallback:undefined})}>重置备用输入</button></div></details>
 <p className="setting-caption">密钥保存在本机，不随完整备份导出。聊天与记忆整理发送到所选服务，按该服务产生用量。</p><div className="settings-form-actions"><button type="button" className="soft-button" disabled={testing||!model.baseUrl||!model.model||!model.key} onClick={()=>void test()}>{testing?'正在测试…':'测试连接'}</button><button type="submit" className="primary" disabled={testing||!model.baseUrl||!model.model||!model.key}>保存模型设置</button></div><p role="status">{notice|| (dirty?'有尚未保存的连接设置':'')}</p></form>;
}
export function WeatherSettings({connections}:{connections:Connections}){
 const [weather,setWeather]=useState(connections.weather),[locating,setLocating]=useState(false),[notice,setNotice]=useState('');const task=useRef<AbortController|null>(null);
 useEffect(()=>()=>task.current?.abort(),[]);
 async function position(){if(locating)return;const controller=new AbortController();task.current=controller;setLocating(true);setNotice('正在获取位置');try{const result=await locate(controller.signal,true);if(!controller.signal.aborted){setWeather(w=>({...w,...result}));setNotice('已填入 '+result.place+'，保存后用于天气。');}}catch(e){if(!controller.signal.aborted)setNotice(e instanceof Error?e.message:'定位失败，可以手动填写位置。');}finally{if(!controller.signal.aborted)setLocating(false);}}
 return <form className="settings-stack" onSubmit={e=>{e.preventDefault();try{connections.apply(connections.model,weather);setNotice('天气位置已保存');}catch(e){setNotice(e instanceof Error?e.message:'位置未保存');}}}><label>天气来源<select value={weather.provider} onChange={e=>setWeather(w=>({...w,provider:e.target.value as typeof w.provider}))}><option value="caiyun">彩云天气</option><option value="open-meteo">Open-Meteo</option></select></label>{weather.provider==='caiyun'&&<label>彩云 Token<input type="password" autoComplete="off" value={weather.key} onChange={e=>setWeather(w=>({...w,key:e.target.value}))}/></label>}<label>地点名称<input maxLength={50} value={weather.place} onChange={e=>setWeather(w=>({...w,place:e.target.value}))}/></label><div className="coordinate-inputs"><label>纬度<input type="number" step="any" min={-90} max={90} required value={weather.lat} onChange={e=>setWeather(w=>({...w,lat:e.target.value}))}/></label><label>经度<input type="number" step="any" min={-180} max={180} required value={weather.lon} onChange={e=>setWeather(w=>({...w,lon:e.target.value}))}/></label></div><p className="setting-caption">点击定位后申请位置权限；也可手动填写坐标。坐标会发给所选天气服务，用于当前地区的天气。</p><button type="button" className="soft-button" disabled={locating} onClick={()=>void position()}><MapPin size={17}/>{locating?'正在定位…':'使用当前位置'}</button><label className="settings-toggle"><span>天气小特效</span><input type="checkbox" checked={weather.effects} onChange={e=>setWeather(w=>({...w,effects:e.target.checked}))}/></label><button className="primary" disabled={locating}>保存天气设置</button><p role="status">{notice}</p></form>;
}
