'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {complete,completionURL,type ModelConfig} from '@/lib/model';
import {defaultModel,resolveModel,validModel} from '@/lib/default-model';
import {coordinates,fetchWeather,isFresh,weatherAdvice,type Weather,type WeatherConfig} from '@/lib/weather';

import {locate} from '@/lib/location';
import {Sun,CloudRain,Cloud,CloudSnow,CloudLightning,CloudFog,RefreshCw,MapPin,Settings} from 'lucide-react';
export function useConnections(){const [model,setModel]=useState<ModelConfig>({baseUrl:'',model:'',key:''});const [weather,setWeather]=useState<WeatherConfig>({provider:'open-meteo',lat:'',lon:'',place:'我的位置',key:'',effects:true});const [loaded,setLoaded]=useState(false);useEffect(()=>{const builtIn=defaultModel();setModel(resolveModel(undefined,builtIn));try{const settings=JSON.parse(localStorage.getItem('luke-connections-v1')||'{}');const persistent=JSON.parse(localStorage.getItem('luke-model-credentials-v1')||'null');const legacy=settings.model?{...settings.model,key:sessionStorage.getItem('luke-model-key')||''}:undefined;setModel(resolveModel(validModel(persistent)?persistent:legacy,builtIn));if(settings.weather){const clean={...settings.weather,provider:'open-meteo' as const,key:''};setWeather(clean);localStorage.setItem('luke-connections-v1',JSON.stringify({...settings,weather:{...clean,key:undefined}}));}sessionStorage.removeItem('luke-weather-key');}catch{}setLoaded(true);},[]);
 function apply(m:ModelConfig,w:WeatherConfig){if(m.baseUrl)completionURL(m.baseUrl);if(m.fallback?.baseUrl)completionURL(m.fallback.baseUrl);if(w.lat||w.lon)coordinates(w.lat,w.lon);const resolved=resolveModel(m,defaultModel());const keys=['luke-model-credentials-v1','luke-connections-v1'],old=keys.map(k=>localStorage.getItem(k));try{localStorage.setItem(keys[0],JSON.stringify(resolved));localStorage.setItem(keys[1],JSON.stringify({model:{baseUrl:resolved.baseUrl,model:resolved.model},weather:{...w,provider:'open-meteo',key:undefined}}));}catch(error){let failed=false;keys.forEach((k,i)=>{try{if(old[i]===null)localStorage.removeItem(k);else localStorage.setItem(k,old[i]!);}catch{failed=true;}});if(failed)throw Error('设置写入中断，请重新打开设置核对；未显示保存成功。');throw error;}try{sessionStorage.setItem('luke-model-key',resolved.key);sessionStorage.removeItem('luke-weather-key');}catch{}setModel(resolved);setWeather({...w,provider:'open-meteo',key:''});}
 function saveWeather(next:WeatherConfig){coordinates(next.lat,next.lon);const settings=JSON.parse(localStorage.getItem('luke-connections-v1')||'{}');localStorage.setItem('luke-connections-v1',JSON.stringify({...settings,weather:{...next,key:undefined}}));sessionStorage.removeItem('luke-weather-key');setWeather({...next,provider:'open-meteo',key:''});}
 return {model,weather,loaded,apply,saveWeather};}
export function useWeather(config:WeatherConfig,loaded:boolean){const [weather,setWeather]=useState<Weather|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[clock,setClock]=useState(Date.now());const request=useRef<AbortController|null>(null);
 const refresh=useCallback(async()=>{if(!loaded||!config.lat||!config.lon)return;request.current?.abort();const controller=new AbortController();request.current=controller;setLoading(true);setError('');try{const result=await fetchWeather(config,AbortSignal.any([controller.signal,AbortSignal.timeout(20000)]));if(!controller.signal.aborted){setWeather(result);setClock(Date.now());}}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'天气获取失败，请重试。');}finally{if(!controller.signal.aborted)setLoading(false);}},[config,loaded]);
 useEffect(()=>{setWeather(null);setError('');setLoading(false);void refresh();const tick=setInterval(()=>{setClock(Date.now());if(document.visibilityState==='visible')void refresh();},5*60000);const wake=()=>{if(document.visibilityState==='visible')void refresh();};document.addEventListener('visibilitychange',wake);return()=>{request.current?.abort();clearInterval(tick);document.removeEventListener('visibilitychange',wake);};},[refresh]);
 const fresh=weather&&isFresh(weather,clock)&&!error;return {weather,error,loading,refresh,fresh,context:fresh?`${config.place}：${weather.label}，${weather.temperature}°C。${weatherAdvice(weather)} ${weather.forecast}；${weather.alert}。数据时间 ${new Date(weather.observedAt).toISOString()}`:''};}
export function WeatherCard({state,config,configure}:{state:ReturnType<typeof useWeather>;config:WeatherConfig;configure:()=>void}){const w=state.weather;const Icon=w?({sun:Sun,cloud:Cloud,rain:CloudRain,snow:CloudSnow,storm:CloudLightning,fog:CloudFog})[w.kind]:Cloud;return <section className={'card weather-card '+(config.effects&&state.fresh?'weather-'+w?.kind:'')}><div className="weather-animation" aria-hidden="true"/><div className="section-label"><MapPin size={17}/>{config.place||'我的天气'}<button className="round" aria-label="天气设置" onClick={configure}><Settings size={16}/></button><button className="round" aria-label="刷新天气" onClick={()=>{if(!config.lat||!config.lon)configure();else void state.refresh();}} disabled={state.loading}><RefreshCw size={16} className={state.loading?'spinning':''}/></button></div>{w?<><div className="weather-reading"><strong>{Math.round(w.temperature)}°</strong><div>{w.label}<small>{state.fresh?'当前天气':'上次天气 · 已过期或更新失败'}</small></div><Icon size={52}/></div><p className="weather-advice">{state.fresh?weatherAdvice(w):'暂时无法确认现在的天气，更新后再看出门提醒。'}</p>{state.fresh&&w.forecast&&<p>{w.forecast}</p>}{state.fresh&&w.days?.length&&<div className="weather-week" aria-label="未来七天天气">{w.days.map((day:any,i:number)=><div className="weather-day" key={day.date}><strong>{i===0?"今天":new Date(day.date+'T12:00:00').toLocaleDateString("zh-CN",{weekday:"short"})}</strong><span>{day.label}</span><b>{Math.round(day.temperature)}°</b></div>)}</div>}{state.fresh&&w.alert&&<div className="weather-alert">气象预警：{w.alert}</div>}</>:<div className="weather-empty"><Icon size={36}/><h2>{state.loading?'正在看看窗外的天气…':'今天的天气，也想替你留意'}</h2><p>设置位置后，就能看到天气与带伞提醒。</p><button className="soft-button" onClick={configure}>设置天气位置</button></div>}{w&&<a className="weather-attribution" href="https://open-meteo.com/" target="_blank" rel="noreferrer">Open-Meteo</a>}{state.error&&<p role="alert" className="form-feedback">{state.error}</p>}</section>;}
