'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {ModelConfig} from '@/lib/model';
import type {DailySong,DailyBook} from '@/lib/daily-picks';
import {dateKey} from '@/lib/companion';
import {appendHistory,generateRecommendation,migrateHistory,readHistory,type Recommendation} from '@/lib/recommendation-history';
export type DailyState={picks?:{date:string;updatedAt:string;songs:DailySong[];book?:DailyBook};loading:boolean;error:string;refresh:()=>void};
export function useDailyPicks(config:ModelConfig|undefined,enabled:boolean,context:string){
 const [history,setHistory]=useState<Recommendation[]>([]),[loading,setLoading]=useState({song:false,book:false}),[error,setError]=useState({song:'',book:''});const requests=useRef<Partial<Record<'song'|'book',AbortController>>>({}),live=useRef({config,enabled,context}),generation=useRef(0);live.current={config,enabled,context};
 const request=useCallback(async(kind:'song'|'book',force=false)=>{const {config,enabled,context}=live.current;if(!enabled||requests.current[kind]||document.hidden)return;if(!config?.baseUrl||!config.model||!config.key){setError(v=>({...v,[kind]:'请先在聊天模型中完成连接配置。'}));return;}try{if(!force&&readHistory().some(v=>v.kind===kind&&v.date===dateKey(new Date())))return;}catch{setError(v=>({...v,[kind]:'历史读取失败，已暂停更新。'}));return;}const version=generation.current,controller=new AbortController();requests.current[kind]=controller;setLoading(v=>({...v,[kind]:true}));setError(v=>({...v,[kind]:''}));try{const result=await generateRecommendation(config,context,kind,controller.signal);if(controller.signal.aborted||generation.current!==version)return;appendHistory(result);setHistory(readHistory());}catch(e){if(!controller.signal.aborted&&generation.current===version)setError(v=>({...v,[kind]:e instanceof Error?e.message:'推荐未更新，原记录保留。'}));}finally{if(requests.current[kind]===controller){delete requests.current[kind];setLoading(v=>({...v,[kind]:false}));}}},[]);
 useEffect(()=>{const sync=()=>{try{migrateHistory();setHistory(readHistory());}catch{setError({song:'历史读取失败，原内容保留。',book:'历史读取失败，原内容保留。'});}};sync();window.addEventListener('luke-recommendations-changed',sync);return()=>window.removeEventListener('luke-recommendations-changed',sync);},[]);
 useEffect(()=>{generation.current++;const wake=()=>{if(document.hidden){Object.values(requests.current).forEach(c=>c?.abort());return;}void request('song');void request('book');};wake();window.addEventListener('online',wake);document.addEventListener('visibilitychange',wake);const timer=setInterval(wake,60000);return()=>{generation.current++;Object.values(requests.current).forEach(c=>c?.abort());requests.current={};setLoading({song:false,book:false});clearInterval(timer);window.removeEventListener('online',wake);document.removeEventListener('visibilitychange',wake);};},[request,enabled,config?.baseUrl,config?.model,config?.key]);
 function state(kind:'song'|'book'):DailyState{const item=history.find(v=>v.kind===kind);return {loading:loading[kind],error:error[kind],refresh:()=>{void request(kind,true);},picks:item?{date:item.date,updatedAt:item.updatedAt,songs:kind==='song'?[{title:item.title,artist:item.creator,thought:item.thought}]:[],book:kind==='book'?{title:item.title,author:item.creator,thought:item.thought,about:item.about??'',kind:item.bookKind??'在读'}:undefined}:undefined};}return {music:state('song'),reading:state('book')};
}
