'use client';
import {useEffect,useState} from 'react';
import {BookOpen,ChevronLeft,ChevronRight,Pencil,RefreshCw} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import {ExpandableNote} from './expandable-note';
import {RecommendationPreferencesDialog} from './recommendation-preferences';
import {RecommendationComment} from './recommendation-comment';
import type {Data} from '@/lib/companion';
import {dateKey} from '@/lib/companion';
import {readHistory,type Recommendation} from '@/lib/recommendation-history';
import type {DailyState} from './daily-picks';
/** No built-in book rotation: browsing uses real saved/generated history only. */
export function ReadingMoment({onNote,onChat,data,save,daily}:{onNote:(text:string)=>void;onChat?:(text:string)=>void;data:Data;save:(patch:Partial<Data>)=>void;daily?:DailyState}){
 const [index,setIndex]=useState(0),[history,setHistory]=useState<Recommendation[]>([]),[editing,setEditing]=useState(false),[title,setTitle]=useState(''),[author,setAuthor]=useState(''),[progress,setProgress]=useState(''),[thought,setThought]=useState(''),[error,setError]=useState('');
 useEffect(()=>{const sync=()=>{try{setHistory(readHistory().filter(x=>x.kind==='book'));}catch{setError('书籍历史读取失败，原记录已保留。');}};sync();window.addEventListener('luke-recommendations-changed',sync);return()=>window.removeEventListener('luke-recommendations-changed',sync);},[]);
 useEffect(()=>setIndex(0),[daily?.picks?.updatedAt]);
 const fresh=daily?.picks?.book,candidates=[...(fresh?[{...fresh,date:daily!.picks!.date}]:[]),...history.map(v=>({title:v.title,author:v.creator,kind:v.bookKind??'在读',about:v.about??'',thought:v.thought,date:v.date})),...(data.books??[]).map(b=>({...b,kind:'我的书',about:b.progress||'',thought:b.thought||'',date:''})),...(data.reading?[{...data.reading,kind:'正在读',about:data.reading.progress??'',thought:data.reading.thought??'',date:''}]:[])];
 const seen=new Set<string>(),books=candidates.filter(b=>{const key=b.title+'\0'+b.author;if(seen.has(key))return false;seen.add(key);return true;}),book=books[Math.min(index,books.length-1)],reading=data.reading;
 const same=(b:{title:string;author:string})=>!!book&&b.title===book.title&&b.author===book.author,saved=book?(data.books?.find(same)??(reading&&same(reading)?reading:undefined)):undefined;
 function edit(add=false){setTitle(add?'':book?.title??'');setAuthor(add?'':book?.author??'');setProgress(add?'':saved?.progress??'');setThought(add?'':saved?.thought??'');setEditing(true);}
 return <section className="reading-moment"><div className="section-label"><BookOpen size={18}/>一起读一本书 <button type="button" onClick={()=>edit(true)}>添加书籍</button></div>{book?<><div className="reading-book"><div className="book-spine" aria-hidden="true"><img src="/images/details210/flower-bookmark.webp" alt="" width={54} height={74}/><span>{book.kind}</span></div><div><h3>《{book.title}》</h3><small>{book.author} · {book.kind}</small><p>{saved?.progress||book.about}</p></div></div><RecommendationComment item={book.date?{kind:'book',title:book.title,creator:book.author,thought:book.thought,date:book.date}:undefined}/>{saved?.thought&&<p>我的感想：{saved.thought}</p>}<div className="reading-browse210"><button type="button" className="round" aria-label="上一本已保存的书" disabled={books.length<2} onClick={()=>setIndex((index+books.length-1)%books.length)}><ChevronLeft size={18}/></button><span>{Math.min(index+1,books.length)} / {books.length}</span><button type="button" className="round" aria-label="下一本已保存的书" disabled={books.length<2} onClick={()=>setIndex((index+1)%books.length)}><ChevronRight size={18}/></button></div><button className="primary" onClick={()=>onChat?.(`一起聊聊《${book.title}》，作者${book.author}。简介：${book.about}。进度：${saved?.progress||'尚未提供，避免剧透'}。感想：${saved?.thought||book.thought}`)}>聊聊这本书</button><ExpandableNote label="管理这本书" title="阅读记录"><div className="reading-actions"><button className="soft-button" type="button" onClick={()=>onNote(`读《${book.title}》 · ${book.author}\n${saved?.progress??''}\n${saved?.thought??''}`)}><Pencil size={15}/>写读后感</button><button className="soft-button" type="button" aria-pressed={!!reading&&same(reading)} onClick={()=>save({reading:reading&&same(reading)?undefined:{...saved,title:book.title,author:book.author,updatedAt:new Date().toISOString()}})}>{reading&&same(reading)?'结束在读':'设为正在读'}</button><button className="soft-button" type="button" onClick={()=>edit()}>编辑进度</button></div></ExpandableNote></>:<div className="reading-empty210"><BookOpen size={32}/><h3>下一本书，一起挑</h3><p>取得推荐或添加自己的书，不再按固定的内置书单轮换。</p></div>}<p role="status">{daily?.loading?'正在结合你的偏好挑选…':error||daily?.error||''}</p><div className="moment-footer"><button className="soft-button" disabled={!daily||daily.loading} onClick={daily?.refresh}><RefreshCw size={16}/>{book?'换一本推荐':'获取推荐'}</button><RecommendationPreferencesDialog/></div>
 <Dialog open={editing} onOpenChange={setEditing}><DialogContent className="settings"><DialogTitle>书籍与阅读进度</DialogTitle><DialogDescription>填写自己的书名、作者和读到的位置。</DialogDescription><form className="settings-stack" onSubmit={e=>{e.preventDefault();if(!title.trim()||!author.trim())return;const entry={title:title.trim(),author:author.trim(),progress:progress.trim(),thought:thought.trim(),updatedAt:new Date().toISOString()};save({books:[...(data.books??[]).filter(b=>b.title!==entry.title||b.author!==entry.author),entry],reading:entry});setEditing(false);}}><label>书名<input required maxLength={120} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>作者<input required maxLength={80} value={author} onChange={e=>setAuthor(e.target.value)}/></label><label>阅读进度<input maxLength={80} value={progress} onChange={e=>setProgress(e.target.value)}/></label><label>感想<textarea rows={3} maxLength={1000} value={thought} onChange={e=>setThought(e.target.value)}/></label><button className="primary">保存并设为正在读</button></form></DialogContent></Dialog></section>;
}
