'use client';
import {useEffect,useState} from 'react';
import {Bookmark,FolderHeart} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {FAVORITES_KEY,parseFavorites,sameFavorite,searchFavorites,type RecommendationFavorite} from '@/lib/recommendation-favorites';
import '@/app/recommendations.css';
import {readHistory,type Recommendation} from '@/lib/recommendation-history';
export function RecommendationComment({item}:{item?:RecommendationFavorite}){
 const [history,setHistory]=useState<Recommendation[]>([]),[showHistory,setShowHistory]=useState(false);
 useEffect(()=>{const read=()=>{try{setHistory(readHistory());}catch{setError('推荐历史无法读取，原数据已保留。');}};read();window.addEventListener('luke-recommendations-changed',read);return()=>window.removeEventListener('luke-recommendations-changed',read);},[]);
 const [items,setItems]=useState<RecommendationFavorite[]>([]),[error,setError]=useState(''),[open,setOpen]=useState(false),[query,setQuery]=useState(''),[kind,setKind]=useState('');
 useEffect(()=>{const read=()=>{try{setItems(parseFavorites(localStorage.getItem(FAVORITES_KEY)||'[]'));setError('');}catch(e){setError(e instanceof Error?e.message:'收藏读取失败');}};read();window.addEventListener('luke-favorites-changed',read);window.addEventListener('storage',read);return()=>{window.removeEventListener('luke-favorites-changed',read);window.removeEventListener('storage',read);};},[]);
 function toggle(value:RecommendationFavorite){try{const current=parseFavorites(localStorage.getItem(FAVORITES_KEY)||'[]');const next=current.some(v=>sameFavorite(v,value))?current.filter(v=>!sameFavorite(v,value)):[value,...current];localStorage.setItem(FAVORITES_KEY,JSON.stringify(next));setItems(next);setError('');window.dispatchEvent(new Event('luke-favorites-changed'));}catch(e){setError(e instanceof Error?e.message:'收藏保存失败，请检查剩余空间');}}
 const saved=!!item&&items.some(v=>sameFavorite(v,item)),filtered=searchFavorites(showHistory?history:items,query,kind);
 return <div className="recommendation-comment">{item&&<blockquote><small>夏彦想说</small><p>{item.thought}</p></blockquote>}<div className="recommendation-actions">{item&&<button className="soft-button" aria-pressed={saved} onClick={()=>toggle(item)}><Bookmark size={16} fill={saved?'currentColor':'none'}/>{saved?'已收藏':'收藏'}</button>}<button className="soft-button" onClick={()=>{setShowHistory(false);setOpen(true);}}><FolderHeart size={16}/> 收藏与历史</button></div>{error&&<p role="alert">{error}</p>}<Dialog open={open} onOpenChange={setOpen}><DialogContent className="recommendation-folder"><DialogTitle>{showHistory?'夏彦的全部推荐历史':'夏彦的推荐收藏'}</DialogTitle><DialogDescription>按歌名、书名、作者、日期或评论内容查找。</DialogDescription><div className="recommendation-actions"><button type="button" className="soft-button" aria-pressed={!showHistory} onClick={()=>setShowHistory(false)}>收藏 {items.length}</button><button type="button" className="soft-button" aria-pressed={showHistory} onClick={()=>setShowHistory(true)}>历史 {history.length}</button></div><input aria-label="搜索推荐收藏" placeholder="搜索作品或他的话…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="recommendation-actions">{[['','全部'],['song','音乐'],['book','书籍']].map(([value,label])=><button className="soft-button" key={value} aria-pressed={kind===value} onClick={()=>setKind(value)}>{label}</button>)}</div><div className="recommendation-list">{filtered.map((v,i)=><article key={i}><small>{v.kind==='song'?'音乐':'书籍'} · {v.date}</small><h3>{v.title}</h3><small>{v.creator}</small><p>{v.thought}</p><button className="text-button" onClick={()=>toggle(v)}>{items.some(f=>sameFavorite(f,v))?'取消收藏':'收藏这段话'}</button></article>)}{!filtered.length&&<p>暂时没有符合条件的记录。</p>}</div></DialogContent></Dialog></div>;
}
