'use client';
import {useEffect,useState} from 'react';
import {motion} from 'motion/react';
import {Sun,Cloud,CloudRain,CloudSnow,CloudLightning,CloudFog,MapPin,Settings,RefreshCw,Thermometer,Wind,Droplets} from 'lucide-react';
import {weatherAdvice,type Weather,type WeatherConfig} from '@/lib/weather';
import {temperatureValue,weatherTime,forecastDayLabel,weatherObservationLabel} from '@/lib/weather-cache';
import {useVisibleMotion} from '@/hooks/use-visible-motion';
import {useReducedMotion} from '@/hooks/use-reduced-motion';
const icons={sun:Sun,cloud:Cloud,rain:CloudRain,snow:CloudSnow,storm:CloudLightning,fog:CloudFog};
export function WeatherScene({kind,enabled,isDay=true}:{kind:Weather['kind'];enabled:boolean;isDay?:boolean}){const {ref,playing}=useVisibleMotion<HTMLDivElement>(enabled);return <div className="weather-scene210" ref={ref} data-weather={kind} data-playing={playing} data-day={isDay} aria-hidden="true"><div className="weather-orb210"/><div className="weather-haze210"/>{[0,1,2].map(i=><svg key={i} className={'weather-cloud210 cloud-'+i} viewBox="0 0 160 70"><path d="M20 60C-5 58 1 27 25 27C27 0 77-4 89 23C104 10 132 17 130 36C161 31 170 63 140 64Z"/></svg>)}{['rain','snow','storm'].includes(kind)&&<div className="weather-particles210">{Array.from({length:18},(_,i)=><i key={i} style={{left:`${5+i*5.3}%`,animationDelay:`${-i*.47}s`,animationDuration:`${kind==='snow'?4+i%4:.9+(i%5)*.17}s`}}/>)}</div>}</div>;}
export function SeasonWeather({state,config,configure}:{state:{weather:Weather|null;fresh:boolean|null;error:string;loading:boolean;refresh:()=>Promise<void>};config:WeatherConfig;configure:()=>void}){const [unit,setUnit]=useState<'C'|'F'>('C'),[forecast,setForecast]=useState<'days'|'hours'>('days');useEffect(()=>{try{setUnit(localStorage.getItem('luke-weather-unit-v210')==='F'?'F':'C');}catch{}},[]);const reduced=useReducedMotion(),w=state.weather,Icon=w?icons[w.kind]:Cloud;const actual=w?temperatureValue(w.temperature,unit):0;
 function toggle(){const value=unit==='C'?'F':'C';setUnit(value);try{localStorage.setItem('luke-weather-unit-v210',value);}catch{}}
 return <section className="card weather-card weather-card210" aria-label="今日天气"><div className="weather-sky210"><header className="weather-head210"><MapPin size={16}/><span title={config.place}>{config.place||'我的天气'}</span><button type="button" className="round" aria-label="天气设置" onClick={configure}><Settings size={17}/></button><button type="button" className="round" aria-label="刷新天气" disabled={state.loading} onClick={()=>config.lat&&config.lon?void state.refresh():configure()}><RefreshCw size={17} className={state.loading?'spinning':''}/></button></header>
 {w?<><div className="weather-summary210"><div className="temperature-window210" aria-label={`${actual} 度${unit==='C'?'摄氏':'华氏'}`}><motion.strong key={actual+unit} initial={reduced?false:{opacity:.4,y:8}} animate={{opacity:1,y:0}} transition={{type:'spring',stiffness:370,damping:30}}>{actual}<span aria-hidden="true">°</span></motion.strong></div><div className="weather-art210"><WeatherScene kind={w.kind} enabled={config.effects&&!!state.fresh} isDay={w.isDay}/></div></div><div className="weather-condition210"><div className="weather-description210"><Icon size={19}/><span>{w.label}</span></div><button type="button" aria-label="切换温度单位" onClick={toggle}>°{unit}<span> / °{unit==='C'?'F':'C'}</span></button></div><p className="weather-whisper210">{state.fresh?weatherAdvice(w):'上次的天气 · 等新的消息到来'}</p><small className="weather-time210">{weatherObservationLabel(w.observedAt,Date.now(),w.utcOffset)} {state.fresh?'更新':'缓存'}</small></>:<div className="weather-empty210"><Cloud size={40}/><h3>{state.loading?'正在看看窗外…':'把窗外的天气带进来'}</h3><button type="button" className="soft-button" onClick={configure}>设置天气位置</button></div>}</div>
 {w&&<div className="weather-bottom210">{(w.apparent!==undefined||w.humidity!==undefined||w.wind!==undefined)&&<div className="weather-metrics210">{w.apparent!==undefined&&<span><Thermometer size={15}/>体感 {temperatureValue(w.apparent,unit)}°</span>}{w.humidity!==undefined&&<span><Droplets size={15}/>{Math.round(w.humidity)}%</span>}{w.wind!==undefined&&<span><Wind size={15}/>{Math.round(w.wind)} km/h</span>}</div>}<div className="weather-forecast-tabs210"><button type="button" aria-pressed={forecast==='days'} onClick={()=>setForecast('days')}>未来七天</button><button type="button" aria-pressed={forecast==='hours'} onClick={()=>setForecast('hours')}>逐小时</button></div><div className="weather-forecast210" data-no-swipe tabIndex={0} aria-label={forecast==='days'?'未来七天天气':'逐小时天气'}>{forecast==='days'?w.days?.length?w.days.map((d,i)=>{const ForecastIcon=icons[d.kind];return <div className="weather-day" key={d.date}><time dateTime={d.date} title={d.date}>{forecastDayLabel(d.date,Date.now(),w.utcOffset)}</time><ForecastIcon size={22}/><span>{d.label}</span><strong className="forecast-temperatures210">{temperatureValue(d.temperature,unit)}°<small>{d.minimum!==undefined?temperatureValue(d.minimum,unit)+'°':''}</small></strong></div>;}):<p>暂无逐日预报，更新后再看看。</p>:w.hours?.length?w.hours.slice(0,12).map(h=>{const HourIcon=icons[h.kind];return <div key={h.at}><time>{weatherTime(h.at,w.utcOffset)}</time><HourIcon size={21}/><strong>{temperatureValue(h.temperature,unit)}°</strong><small>{h.rain===undefined?'—':h.rain+'%'}</small></div>;}):<p>暂无逐小时数据，下次更新再看看。</p>}</div>{state.fresh&&w.forecast&&<p className="weather-advice">{w.forecast}</p>}</div>}
 {state.error&&<p className="weather-error210" role="alert">{w?'更新未成功，保留同地点的上次天气。':state.error}</p>}</section>;
}
