'use client';
import {useEffect,useRef,useState} from 'react';
import {Package,Upload,FileText,Download,ArrowLeft,ChevronRight,Trash2,RefreshCw} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import {saveBackupFile} from '@/lib/mobile';
import {emptySkills,readSkillStore,writeSkillStore,mergeSkill,inspectSkillFile,listRepoSkills,fetchRepoSkill,digestSkill,SKILLS_EVENT,SKILLS_KEY,type SkillStore,type InstalledSkill,type RepoSkill} from '@/lib/chat-skills';
export function SkillsManager({open,onClose}:{open:boolean;onClose:()=>void}){
 const [store,setStore]=useState<SkillStore>(emptySkills),[error,setError]=useState(''),[busy,setBusy]=useState(false),[url,setURL]=useState(''),[candidates,setCandidates]=useState<InstalledSkill[]>([]),[choices,setChoices]=useState<RepoSkill[]>([]),[detail,setDetail]=useState<string|null>(null),[file,setFile]=useState('SKILL.md');
 const controller=useRef<AbortController|null>(null),revision=useRef(0),alive=useRef(false);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;controller.current?.abort();};},[]);
 useEffect(()=>{if(!open){controller.current?.abort();controller.current=null;setBusy(false);return;}const sync=()=>{try{setStore(readSkillStore());setError('');}catch(e){setError(e instanceof Error?e.message:'技能读取失败。');}};sync();const change=(e:StorageEvent)=>{if(e.key===SKILLS_KEY||e.key===null)sync();};window.addEventListener('storage',change);return()=>window.removeEventListener('storage',change);},[open]);
 const selected=store.items.find(s=>s.id===detail);
 function cancel(){controller.current?.abort();controller.current=null;setBusy(false);}
 async function inspect(action:(signal:AbortSignal)=>Promise<void>){cancel();const c=new AbortController();controller.current=c;setError('');setBusy(true);try{revision.current=readSkillStore().revision;await action(c.signal);}catch(e){if(!c.signal.aborted&&alive.current)setError(e instanceof Error?e.message:'技能检查未完成。');}finally{if(controller.current===c){controller.current=null;if(alive.current)setBusy(false);}}}
 function save(next:SkillStore,expected=store.revision){try{const result=writeSkillStore(next,expected);setStore(result);setError('');return result;}catch(e){setError(e instanceof Error?e.message:'保存失败。');return null;}}
 async function toggleSkill(skill:InstalledSkill,enabled:boolean){try{const current=readSkillStore();if(current.revision!==store.revision)throw Error('技能目录已变化，请重新打开后操作。');if(enabled&&current.items.filter(s=>s.enabled).length>=3)throw Error('最多同时启用 3 个技能。');if(enabled&&await digestSkill(skill.files)!==skill.digest)throw Error('该技能内容校验不匹配，请重新导入。');if(!alive.current)return;save({...current,items:current.items.map(s=>s.id===skill.id?{...s,enabled}:s)},current.revision);}catch(e){setError(e instanceof Error?e.message:'技能状态未保存。');}}
 function install(skill:InstalledSkill){try{const current=readSkillStore();if(current.revision!==revision.current)throw Error('检查期间技能目录发生变化，请重新读取安装内容。');const old=current.items.find(s=>s.id===skill.id);if(old&&!confirm(`替换“${skill.name}”？新内容默认停用，旧资料将被替换。`))return;const result=save(mergeSkill(current,skill,!!old),current.revision);if(result){revision.current=result.revision;setCandidates(v=>v.filter(c=>c.id!==skill.id));}}catch(e){setError(e instanceof Error?e.message:'安装未完成。');}}
 return <Dialog open={open} onOpenChange={v=>{if(!v){cancel();onClose();}}}><DialogContent className="settings skills-panel210" fixedHeader={<header className="workspace-panel-head210">{selected&&<button className="round" type="button" aria-label="返回技能列表" onClick={()=>setDetail(null)}><ArrowLeft size={18}/></button>}<div><DialogTitle>{selected?selected.name:'Skills · 技能'}</DialogTitle><DialogDescription>{selected?'方法与参考资料':'安装后默认停用，由你选择用于聊天'}</DialogDescription></div></header>}>
 {selected?<div className="settings-stack"><p>{selected.description}</p><small className="skill-origin210">{selected.source}</small><label>资料文件<select aria-label="技能资料文件" value={file} onChange={e=>setFile(e.target.value)}>{Object.keys(selected.files).map(n=><option key={n}>{n}</option>)}</select></label><pre className="skill-document210" tabIndex={0}>{selected.files[file]??selected.files['SKILL.md']}</pre><button className="soft-button" type="button" onClick={()=>saveBackupFile(selected.name+'-SKILL.md',selected.files['SKILL.md'])}><Download size={16}/>导出技能说明</button>{selected.ignored.length>0&&<p>未导入脚本或二进制：{selected.ignored.join('、')}</p>}</div>:<div className="settings-stack">
 <div className="skill-boundary210"><Package size={25}/><p>导入 SKILL.md、ZIP 或公开 GitHub 技能。启用的正文与相关资料会发送给你配置的模型；不执行脚本、不授予手机权限。</p></div>
 <section className="preference-card"><h3>安装技能</h3><label className="skill-upload210"><Upload size={18}/>从手机导入<input type="file" aria-label="导入技能文件" accept=".md,.zip" disabled={busy} onChange={e=>{const f=e.currentTarget.files?.[0];e.currentTarget.value='';if(f)void inspect(async signal=>{const result=await inspectSkillFile(f,signal);signal.throwIfAborted();setCandidates(result);setChoices([]);});}}/></label>
 <form className="skill-repo210" onSubmit={e=>{e.preventDefault();void inspect(async signal=>{const result=await listRepoSkills(url,signal);signal.throwIfAborted();setChoices(result);setCandidates([]);});}}><label>GitHub 仓库或目录<input type="url" aria-label="技能 GitHub 地址" required value={url} onChange={e=>setURL(e.target.value)} placeholder="https://github.com/作者/仓库"/></label><button className="soft-button" disabled={busy||!url.trim()}><Download size={16}/>读取技能</button></form>
 {busy&&<div role="status" className="skill-busy210">正在检查资料…<button type="button" onClick={cancel}>取消</button></div>}
 {choices.length>0&&<div className="skill-repo-list210">{choices.map(c=><button type="button" key={c.path} disabled={busy} onClick={()=>void inspect(async signal=>{const result=await fetchRepoSkill(c,signal);signal.throwIfAborted();setCandidates([result]);setChoices([]);})}><FileText size={17}/><span>{c.path.slice(0,-9)||c.repo}</span><ChevronRight size={16}/></button>)}</div>}
 {candidates.map(c=><article className="skill-candidate210" key={c.id}><strong>{c.name}</strong><p>{c.description}</p><small>{Object.keys(c.files).length} 个文本文件{c.ignored.length?` · 忽略 ${c.ignored.length} 个脚本或二进制`:''}</small><details><summary>查看安装内容</summary><pre className="skill-document210">{c.files['SKILL.md']}</pre></details><button type="button" className="primary" onClick={()=>install(c)}>确认安装</button></article>)}
 </section><section className="installed-skills210"><h3>已安装 · {store.items.length}</h3>{!store.items.length&&<p className="empty">先导入一份你信任的技能资料。</p>}{store.items.map(s=><article key={s.id}><button className="skill-title210" type="button" onClick={()=>{setDetail(s.id);setFile('SKILL.md');}}><FileText size={20}/><span><strong>{s.name}</strong><small>{s.description}</small></span><ChevronRight size={16}/></button><div className="skill-actions210"><label><input role="switch" type="checkbox" aria-label={`启用技能 ${s.name}`} checked={s.enabled} onChange={e=>void toggleSkill(s,e.target.checked)}/>用于聊天</label>{s.trackingURL&&<button type="button" className="round" aria-label={`检查技能更新 ${s.name}`} onClick={()=>{setURL(s.trackingURL!);void inspect(async signal=>{const results=await listRepoSkills(s.trackingURL!,signal);signal.throwIfAborted();setChoices(results);setCandidates([]);});}}><RefreshCw size={16}/></button>}<button type="button" className="round" aria-label={`卸载技能 ${s.name}`} onClick={()=>{if(confirm(`卸载“${s.name}”？不会删除聊天。`))save({...store,items:store.items.filter(item=>item.id!==s.id)});}}><Trash2 size={16}/></button></div></article>)}</section></div>}
 {error&&<p className="workspace-error210" role="alert">{error}</p>}
 </DialogContent></Dialog>;
}
