import {Inflate} from 'fflate';
import {networkFetch} from './mobile.ts';
export const SKILLS_KEY='luke-chat-skills-v210';
export const SKILLS_EVENT='luke-skills-change';
export const SKILL_LIMITS={zip:8*1024*1024,file:128*1024,total:2*1024*1024,entries:512,installed:40,enabled:3};
export type InstalledSkill={id:string;name:string;description:string;body:string;files:Record<string,string>;source:string;trackingURL?:string;digest:string;enabled:boolean;installedAt:string;ignored:string[]};
export type SkillStore={version:1;revision:number;items:InstalledSkill[]};
export const emptySkills=():SkillStore=>({version:1,revision:0,items:[]});
export function safeSkillPath(path:string){if(typeof path!=='string'||path.length>240||path.startsWith('/')||/[\\:\x00-\x1f]/.test(path)||path.split('/').length>12||path.split('/').some(p=>!p||p==='..'||p==='.'||['__proto__','prototype','constructor'].includes(p)))throw Error('技能包包含不安全的路径。');return path.normalize('NFC');}
function quoted(v:string){v=v.trim();if(v.startsWith('"')){try{const s=JSON.parse(v);if(typeof s==='string')return s;}catch{}throw Error('技能字段引号格式不正确。');}if(v.startsWith("'")){if(!v.endsWith("'"))throw Error('技能字段引号不完整。');return v.slice(1,-1).replaceAll("''", "'");}if(/^[&*!{\[]/.test(v))throw Error('技能名称和描述必须是普通文本。');return v.replace(/\s+#.*$/,'').trim();}
export function parseSkillText(raw:string){if(typeof raw!=='string'||new TextEncoder().encode(raw).length>SKILL_LIMITS.file||raw.includes('\0'))throw Error('SKILL.md 不是有效文本或超过 128 KB。');const match=raw.replace(/^\uFEFF/,'').replace(/\r\n/g,'\n').match(/^---\n([\s\S]*?)\n---(?:\n|$)([\s\S]*)$/);if(!match)throw Error('缺少 SKILL.md 的名称和描述字段。');const fields:Record<string,string>=Object.create(null),lines=match[1].split('\n');for(let i=0;i<lines.length;i++){const field=lines[i].match(/^(name|description):\s*(.*)$/);if(!field)continue;if(field[1] in fields)throw Error('技能字段重复。');let value=field[2];if(/^[>|][-+]?$/.test(value)){const words=[];while(i+1<lines.length&&(/^\s/.test(lines[i+1])||!lines[i+1].trim()))words.push(lines[++i].trim());fields[field[1]]=words.join(value[0]==='>'?' ':'\n').trim();}else fields[field[1]]=quoted(value);}if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(fields.name??'')||fields.name.length>64)throw Error('name 需用小写英文、数字和连字符，最多 64 字。');if(!fields.description?.trim()||fields.description.length>1024||!match[2].trim())throw Error('技能需要描述（最多 1024 字）与正文。');return {name:fields.name,description:fields.description,body:match[2].trim()};}
export async function digestSkill(files:Record<string,string>){if(!crypto.subtle)throw Error('当前页面不支持安全内容校验，请在安装版中导入技能。');const data=new TextEncoder().encode(JSON.stringify(Object.entries(files).sort(([a],[b])=>a.localeCompare(b))));const hash=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('');}
export function parseSkillStore(value:unknown):SkillStore{const v=value as SkillStore;if(!v||v.version!==1||!Number.isSafeInteger(v.revision)||v.revision<0||!Array.isArray(v.items)||v.items.length>SKILL_LIMITS.installed)throw Error('技能目录无法读取，原数据未覆盖。');const seen=new Set<string>();let size=0;const items=v.items.map(s=>{if(!s||typeof s.source!=='string'||s.source.length>600||typeof s.digest!=='string'||!/^[a-f0-9]{64}$/.test(s.digest)||typeof s.enabled!=='boolean'||!s.files||typeof s.files!=='object'||Array.isArray(s.files)||Object.keys(s.files).length>512||!Array.isArray(s.ignored)||s.ignored.length>512||s.ignored.some(x=>typeof x!=='string'||x.length>240)||typeof s.installedAt!=='string'||!Number.isFinite(Date.parse(s.installedAt)))throw Error('技能记录不完整。');const files:Record<string,string>=Object.create(null);for(const [path,text]of Object.entries(s.files)){safeSkillPath(path);if(typeof text!=='string'||text.includes('\0'))throw Error('技能资料无效。');const n=new TextEncoder().encode(text).length;size+=n;if(n>SKILL_LIMITS.file||size>SKILL_LIMITS.total)throw Error('技能资料超出容量上限。');files[path]=text;}const meta=parseSkillText(files['SKILL.md']);if(s.id!==meta.name||s.name!==meta.name||s.description!==meta.description||s.body!==meta.body||seen.has(s.id))throw Error('技能身份或内容不一致。');if(s.trackingURL!==undefined){if(typeof s.trackingURL!=='string')throw Error('来源地址无效');parseSkillRepo(s.trackingURL);}seen.add(s.id);return {...s,files};});if(items.filter(s=>s.enabled).length>3)throw Error('同时启用的技能超过 3 个，请先检查目录。');return {...v,items};}
export function readSkillStore(){return parseSkillStore(JSON.parse(localStorage.getItem(SKILLS_KEY)??JSON.stringify(emptySkills())));}
export function writeSkillStore(value:SkillStore,expected:number){const old=readSkillStore();if(old.revision!==expected)throw Error('另一个页面已更新技能，请重新载入后操作。');const next=parseSkillStore({...value,revision:expected+1});try{localStorage.setItem(SKILLS_KEY,JSON.stringify(next));}catch{throw Error('本机未能保存技能，原目录仍保留。');}window.dispatchEvent(new Event(SKILLS_EVENT));return next;}
export function mergeSkill(store:SkillStore,skill:InstalledSkill,replace=false){const items=store.items.filter(s=>s.id!==skill.id);if(items.length!==store.items.length&&!replace)throw Error('已有同名技能，需要确认替换。');return parseSkillStore({...store,items:[...items,{...skill,enabled:false}]});}
export function skillPayload(store:SkillStore,query:string){let budget=16000;const terms=query.toLocaleLowerCase().match(/[a-z0-9]{3,}|[\u3400-\u9fff]{2}/g)??[];return store.items.filter(s=>s.enabled).map(s=>{if(s.body.length>budget)throw Error(`技能 ${s.name} 正文过长，请精简或停用后再发送。`);budget-=s.body.length;const refs:Record<string,string>={};for(const [p,t]of Object.entries(s.files).sort(([a],[b])=>a.localeCompare(b))){if(p==='SKILL.md'||p.startsWith('scripts/')||!terms.some(w=>(p+' '+t.slice(0,1200)).toLowerCase().includes(w))||t.length>Math.min(3000,budget)||Object.keys(refs).length>=2)continue;refs[p]=t;budget-=t.length;}return {name:s.name,description:s.description,method:s.body,references:refs,availableFiles:Object.keys(s.files),capabilities:'text-only; no code execution, device operations or extra permissions'};});}
const decode=(bytes:Uint8Array)=>new TextDecoder('utf-8',{fatal:true}).decode(bytes);
const isText=(path:string)=>/\.(md|txt|csv|json|ya?ml)$/i.test(path)||/(^|\/)(LICENSE|NOTICE)(\.[^/]*)?$/i.test(path);
const crcTable=Uint32Array.from({length:256},(_,n)=>{let c=n;for(let j=0;j<8;j++)c=c&1?0xedb88320^(c>>>1):c>>>1;return c>>>0;});
function crc(bytes:Uint8Array){let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0;}
/** Validate all central-directory entries before extraction; never write a filesystem path. */
export async function unzipSkill(bytes:Uint8Array,signal?:AbortSignal){if(bytes.length<22||bytes.length>SKILL_LIMITS.zip)throw Error('ZIP 需完整且小于 8 MB。');const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),need=(p:number,n:number)=>{if(p<0||p+n>bytes.length)throw Error('ZIP 已损坏。');};let end=-1;for(let p=bytes.length-22;p>=Math.max(0,bytes.length-65557);p--){if(view.getUint32(p,true)===0x06054b50&&p+22+view.getUint16(p+20,true)===bytes.length){end=p;break;}}if(end<0)throw Error('不是完整 ZIP。');const count=view.getUint16(end+10,true),start=view.getUint32(end+16,true),length=view.getUint32(end+12,true);if(count>512||count!==view.getUint16(end+8,true)||view.getUint16(end+4,true)||view.getUint16(end+6,true)||start+length!==end)throw Error('ZIP 分卷、ZIP64 或文件过多，不支持导入。');let at=start,total=0;const seen=new Set<string>();type Row={path:string;method:number;size:number;packed:number;offset:number;crc:number;flags:number;raw:string};const rows:Row[]=[];
 for(let i=0;i<count;i++){signal?.throwIfAborted();need(at,46);if(view.getUint32(at,true)!==0x02014b50)throw Error('ZIP 目录损坏。');const n=view.getUint16(at+28,true),x=view.getUint16(at+30,true),c=view.getUint16(at+32,true);need(at+46,n+x+c);const raw=decode(bytes.subarray(at+46,at+46+n)),directory=raw.endsWith('/'),path=safeSkillPath(directory?raw.slice(0,-1):raw);if(seen.has(path.toLowerCase())||((view.getUint32(at+38,true)>>>16)&0xf000)===0xa000||view.getUint16(at+8,true)&1)throw Error('ZIP 有重复路径、符号链接或加密文件。');seen.add(path.toLowerCase());const row={path,raw,method:view.getUint16(at+10,true),flags:view.getUint16(at+8,true),size:view.getUint32(at+24,true),packed:view.getUint32(at+20,true),crc:view.getUint32(at+16,true),offset:view.getUint32(at+42,true)};total+=row.size;if(total>SKILL_LIMITS.total||row.size>SKILL_LIMITS.file||![0,8].includes(row.method)||row.offset>=start)throw Error('技能文件超限或压缩方式不支持。');if(!directory)rows.push(row);at+=46+n+x+c;}
 if(at!==end)throw Error('ZIP 目录长度不符。');const files:Record<string,string>=Object.create(null),ignored:string[]=[],regions:[number,number][]=[];for(const row of rows){signal?.throwIfAborted();const p=row.offset;need(p,30);const n=view.getUint16(p+26,true),extra=view.getUint16(p+28,true),begin=p+30+n+extra,last=begin+row.packed;need(begin,row.packed);if(view.getUint32(p,true)!==0x04034b50||view.getUint16(p+6,true)!==row.flags||view.getUint16(p+8,true)!==row.method||decode(bytes.subarray(p+30,p+30+n))!==row.raw||last>start||regions.some(([a,b])=>p<b&&last>a))throw Error('ZIP 本地头或重叠区域校验失败。');regions.push([p,last]);if(!isText(row.path)||row.path.split('/').includes('scripts')){ignored.push(row.path);continue;}const packed=bytes.subarray(begin,last);let content:Uint8Array;if(row.method===0)content=packed;else{const parts:Uint8Array[]=[];let actual=0;const inflater=new Inflate(chunk=>{actual+=chunk.length;if(actual>row.size)throw Error('解压大小与声明不符。');parts.push(chunk);});for(let o=0;o<packed.length;o+=1024){signal?.throwIfAborted();inflater.push(packed.subarray(o,Math.min(o+1024,packed.length)),o+1024>=packed.length);}content=new Uint8Array(actual);let index=0;for(const part of parts){content.set(part,index);index+=part.length;}}if(content.length!==row.size||crc(content)!==row.crc)throw Error('技能 ZIP 校验失败，请重新下载。');files[row.path]=decode(content);await Promise.resolve();}return {files,ignored};}
export async function discoverSkillFiles(files:Record<string,string>,source:string,ignored:string[]=[],trackingURL?:string){const mains=Object.keys(files).filter(p=>p==='SKILL.md'||p.endsWith('/SKILL.md'));if(!mains.length||mains.length>40)throw Error('请使用包含 1～40 个 SKILL.md 的文件或目录。');const results:InstalledSkill[]=[];for(const main of mains){const prefix=main.slice(0,-8),meta=parseSkillText(files[main]),subset:Record<string,string>=Object.create(null);for(const [p,t]of Object.entries(files))if(p.startsWith(prefix)&&!mains.some(other=>other!==main&&other.startsWith(prefix)&&p.startsWith(other.slice(0,-8))))subset[safeSkillPath(p.slice(prefix.length))]=t;results.push({id:meta.name,...meta,files:subset,source,trackingURL,enabled:false,installedAt:new Date().toISOString(),digest:await digestSkill(subset),ignored:ignored.filter(p=>p.startsWith(prefix)).map(p=>p.slice(prefix.length))});}if(new Set(results.map(s=>s.id)).size!==results.length)throw Error('包中存在重名技能，请分开导入。');return results;}
export async function inspectSkillFile(file:File,signal?:AbortSignal){if(file.size===0||file.size>SKILL_LIMITS.zip)throw Error('请选择不超过 8 MB 的 SKILL.md 或 ZIP。');const bytes=new Uint8Array(await file.arrayBuffer());signal?.throwIfAborted();if(/\.zip$/i.test(file.name)){const pack=await unzipSkill(bytes,signal);return discoverSkillFiles(pack.files,'本地 ZIP：'+file.name,pack.ignored);}if(!/\.md$/i.test(file.name))throw Error('请选择 Markdown 或 ZIP。');return discoverSkillFiles({'SKILL.md':decode(bytes)},'本地文件：'+file.name);}
export function parseSkillRepo(value:string){if(typeof value!=='string'||value.length>600)throw Error('仓库地址过长。');const raw=value.trim();const rawPath=raw.replace(/^https:\/\/[^/]+/i,'').split(/[?#]/)[0];for(const part of rawPath.split('/').filter(Boolean)){const decoded=decodeURIComponent(part);if(decoded==='..'||decoded==='.'||/[\\/\x00-\x1f]/.test(decoded))throw Error('仓库路径无效。');}const u=new URL(raw);if(u.protocol!=='https:'||u.hostname!=='github.com'||u.port||u.search||u.hash||u.username||u.password)throw Error('请填写公开 GitHub 仓库、目录或 SKILL.md 地址。');const parts=u.pathname.split('/').filter(Boolean).map(decodeURIComponent);if(parts.length<2||!parts.slice(0,2).every(p=>/^[\w.-]+$/.test(p))||parts.some(p=>p==='..'||p==='.'||/[\\\x00-\x1f]/.test(p)))throw Error('仓库地址无效。');if(parts.length>2&&!['tree','blob'].includes(parts[2]))throw Error('请选择仓库根目录、tree 目录或 blob 文件地址。');return {owner:parts[0],repo:parts[1].replace(/\.git$/,''),ref:parts[3],path:parts.slice(4).join('/')};}
export type RepoSkill={owner:string;repo:string;commit:string;path:string;sourceURL:string;files:{path:string;size:number}[]};
async function bounded(url:string,max:number,signal:AbortSignal){const timer=new AbortController(),abort=()=>timer.abort();signal.addEventListener('abort',abort,{once:true});const id=setTimeout(abort,20000);try{signal.throwIfAborted();const response=await networkFetch(url,{signal:timer.signal,credentials:'omit',redirect:'error',headers:{Accept:'application/json'}});if(!response.ok)throw Error(`GitHub 返回 ${response.status}，公开接口可能限流，请稍后重试。`);const text=await response.text();if(new TextEncoder().encode(text).length>max)throw Error('仓库文件超出大小限制。');return text;}finally{clearTimeout(id);signal.removeEventListener('abort',abort);}}
export async function listRepoSkills(url:string,signal:AbortSignal):Promise<RepoSkill[]>{const {owner,repo,ref,path}=parseSkillRepo(url),base=`https://api.github.com/repos/${owner}/${repo}`;const info=JSON.parse(await bounded(base,100000,signal));if(info.private)throw Error('仅支持公开仓库，不需要粘贴 GitHub 密钥。');const commit=JSON.parse(await bounded(base+'/commits/'+encodeURIComponent(ref||info.default_branch),2*1024*1024,signal));if(!/^[a-f0-9]{40}$/.test(commit.sha))throw Error('无法固定仓库版本。');const tree=JSON.parse(await bounded(base+'/git/trees/'+commit.sha+'?recursive=1',2*1024*1024,signal));if(tree.truncated||!Array.isArray(tree.tree))throw Error('仓库过大，请改为导入单个技能 ZIP。');const mains=tree.tree.filter((f:any)=>f.type==='blob'&&(f.path==='SKILL.md'||f.path.endsWith('/SKILL.md'))&&(!path||f.path===path||f.path.startsWith(path+'/')));if(!mains.length||mains.length>100)throw Error('未找到技能，或技能超过100个；请选择具体目录。');return mains.map((m:any)=>{const prefix=m.path.slice(0,-8),files=tree.tree.filter((f:any)=>f.type==='blob'&&f.path.startsWith(prefix)&&!mains.some((other:any)=>other.path!==m.path&&other.path.startsWith(prefix)&&f.path.startsWith(other.path.slice(0,-8))));if(files.some((f:any)=>!['100644','100755'].includes(f.mode)))throw Error('技能目录含不支持的链接。');return {owner,repo,commit:commit.sha,path:m.path,sourceURL:url,files:files.map((f:any)=>({path:safeSkillPath(f.path),size:f.size}))};});}
export async function fetchRepoSkill(item:RepoSkill,signal:AbortSignal){let total=0;const files:Record<string,string>=Object.create(null),ignored:string[]=[];if(item.files.length>512)throw Error('技能文件过多。');for(const f of item.files){signal.throwIfAborted();if(!isText(f.path)||f.path.split('/').includes('scripts')){ignored.push(f.path);continue;}total+=f.size;if(!Number.isSafeInteger(f.size)||f.size<0||f.size>SKILL_LIMITS.file||total>SKILL_LIMITS.total)throw Error('技能文件过大。');files[f.path]=await bounded(`https://raw.githubusercontent.com/${item.owner}/${item.repo}/${item.commit}/`+f.path.split('/').map(encodeURIComponent).join('/'),SKILL_LIMITS.file,signal);}const results=await discoverSkillFiles(files,`https://github.com/${item.owner}/${item.repo}/tree/${item.commit}/${item.path.slice(0,-8)}`,ignored,item.sourceURL);if(results.length!==1)throw Error('技能目录与选择不符。');return results[0];}

export async function checkedSkillPayload(store:SkillStore,query:string,signal?:AbortSignal){signal?.throwIfAborted();for(const skill of store.items.filter(s=>s.enabled)){if(await digestSkill(skill.files)!==skill.digest)throw Error(`技能 ${skill.name} 的内容校验不匹配，请重新导入后启用。`);signal?.throwIfAborted();}if(readSkillStore().revision!==store.revision)throw Error('技能在准备请求时发生变化，请重新发送。');return skillPayload(store,query);}
