import {BUNDLED_HOLIDAYS,parseStaticHoliday,parseApiHoliday,holidayIndex,scheduleSignature,type HolidayDocument} from './holiday-data.ts';
export const HOLIDAY_CACHE='luke-holiday-cache-v209',HOLIDAY_PREFS='luke-calendar-settings-v209';
export type HolidayPolicy={autoUpdate:boolean;fallback:boolean};
type Entry={document:HolidayDocument;origin:'static'|'api';updatedAt:number};
type StorageAPI=Pick<Storage,'getItem'|'setItem'|'removeItem'>;
export const chinaYear=(at:number)=>new Date(at+28800000).getUTCFullYear();
export const holidayURLs=(year:number)=>({static:`https://cdn.jsdelivr.net/gh/NateScarlet/holiday-cn@master/${year}.json`,api:`https://timor.tech/api/holiday/year/${year}/`});
export class HolidayRepository{
 private cache=new Map<number,Entry>();private attempts=new Map<number,number>();private checked=new Map<number,number>();private pending=new Map<number,Promise<void>>();private active=new Map<number,AbortController>();private notes=new Map<number,string>();private listeners=new Set<()=>void>();private rev=0;private epoch=0;private queue=Promise.resolve();private policy:HolidayPolicy={autoUpdate:true,fallback:true};
 private readonly store:StorageAPI|undefined;private readonly fetcher:(url:string,init:RequestInit)=>Promise<Response>;private readonly now:()=>number;private readonly available:()=>boolean;private readonly timeout:number;
 constructor(store:StorageAPI|undefined,fetcher:(url:string,init:RequestInit)=>Promise<Response>,now=Date.now,available=()=>true,timeout=8000){this.store=store;this.fetcher=fetcher;this.now=now;this.available=available;this.timeout=timeout;this.load();}
 get revision(){return this.rev;}get settings(){return this.policy;}subscribe=(f:()=>void)=>{this.listeners.add(f);return()=>{this.listeners.delete(f);};};private emit(){this.rev++;this.listeners.forEach(f=>f());}
 private reviewed(doc:HolidayDocument){const old=BUNDLED_HOLIDAYS.find(d=>d.year===doc.year);if(old&&scheduleSignature(old)!==scheduleSignature(doc))throw Error('在线安排与本版已校对日期不同，已保留本地安排。');}
 private load(){try{const p=JSON.parse(this.store?.getItem(HOLIDAY_PREFS)||'{}');this.policy={autoUpdate:p.autoUpdate!==false,fallback:p.fallback!==false};}catch{}try{const raw=this.store?.getItem(HOLIDAY_CACHE);if(!raw||raw.length>400000)return;const p=JSON.parse(raw);if(p.version!==1||!Array.isArray(p.entries)||p.entries.length>12)return;for(const row of p.entries)try{const y=row.document?.year;if(!Number.isInteger(y)||y<2007||y>chinaYear(this.now())+1||!['static','api'].includes(row.origin)||!Number.isFinite(row.updatedAt)||row.updatedAt<0||row.updatedAt>this.now()+300000)continue;const doc=row.origin==='static'?parseStaticHoliday(row.document,y):parseApiHoliday({code:0,holiday:Object.fromEntries(row.document.days.map((d:any)=>[d.date.slice(5),{date:d.date,name:d.name,holiday:d.isOffDay}]))},y);this.reviewed(doc);this.cache.set(y,{document:doc,origin:row.origin,updatedAt:row.updatedAt});}catch{}for(const [m,target]of [[p.attempts,this.attempts],[p.checked,this.checked]] as const)for(const [key,value]of Object.entries(m??{})){const y=Number(key);if(y>=2007&&y<=chinaYear(this.now())+1&&typeof value==='number'&&Number.isFinite(value)&&value>=0&&value<=this.now())target.set(y,value);}}catch{}}
 snapshot(year:number){const docs=new Map(BUNDLED_HOLIDAYS.map(d=>[d.year,d]));this.cache.forEach((c,y)=>docs.set(y,c.document));const days=holidayIndex(year,[...docs.values()]);return {year,days,complete:docs.has(year),origin:this.cache.get(year)?.origin??(BUNDLED_HOLIDAYS.some(d=>d.year===year)?'bundled':'none'),loading:this.active.has(year),message:this.notes.get(year)||'',lastChecked:this.checked.get(year)??0};}
 setPolicy(patch:Partial<HolidayPolicy>){const next={...this.policy,...patch};this.store?.setItem(HOLIDAY_PREFS,JSON.stringify(next));this.policy=next;this.cancel();this.emit();}
 reload(){this.cancel(false);this.cache.clear();this.checked.clear();this.attempts.clear();this.notes.clear();this.load();this.emit();}
 cancel(persist=true){this.epoch++;this.active.forEach((c,y)=>{this.attempts.delete(y);c.abort();});this.active.clear();this.pending.clear();if(persist)this.persist();this.emit();}
 private persist(){const entries=[...this.cache.values()].sort((a,b)=>b.updatedAt-a.updatedAt).slice(0,12);const limited=(m:Map<number,number>)=>Object.fromEntries([...m].sort((a,b)=>b[1]-a[1]).slice(0,32));try{this.store?.setItem(HOLIDAY_CACHE,JSON.stringify({version:1,entries,attempts:limited(this.attempts),checked:limited(this.checked)}));return !!this.store;}catch{return false;}}
 private allowed(year:number,manual:boolean){if(!this.available()||!Number.isInteger(year)||year<2007||year>chinaYear(this.now())+1||(!manual&&!this.policy.autoUpdate))return false;const last=this.attempts.get(year);if(last!==undefined&&this.now()-last<(manual?60000:12*3600000))return false;const checked=this.checked.get(year);return manual||checked===undefined||this.now()-checked>=(this.cache.get(year)?.origin==='api'?86400000:7*86400000);}
 refresh(year:number,manual=false):Promise<void>{const old=this.pending.get(year);if(old)return old;if(!this.allowed(year,manual))return Promise.resolve();const epoch=this.epoch;let task:Promise<void>;task=this.queue.then(async()=>{if(epoch!==this.epoch||!this.allowed(year,manual))return;const controller=new AbortController();this.active.set(year,controller);this.attempts.set(year,this.now());this.notes.delete(year);this.persist();this.emit();try{const urls=holidayURLs(year);let doc:HolidayDocument,origin:'static'|'api'='static';try{doc=parseStaticHoliday(await this.request(urls.static,controller.signal),year);this.reviewed(doc);}catch(e){if(controller.signal.aborted||this.snapshot(year).complete||!this.policy.fallback)throw e;origin='api';doc=parseApiHoliday(await this.request(urls.api,controller.signal),year);this.reviewed(doc);}if(controller.signal.aborted||epoch!==this.epoch)return;this.cache.set(year,{document:doc,origin,updatedAt:this.now()});this.checked.set(year,this.now());if(!this.persist())this.notes.set(year,'本次已取得安排，但缓存未能保存，退出后仍使用原本地数据。');}catch(e){if(!controller.signal.aborted&&epoch===this.epoch)this.notes.set(year,e instanceof Error&&e.message.includes('已校对')?e.message:this.snapshot(year).complete?'网络暂不可用，保留本地安排。':'暂未取得完整年度安排，不推算休班。');}finally{if(epoch===this.epoch){this.active.delete(year);this.emit();}}}).finally(()=>{if(this.pending.get(year)===task)this.pending.delete(year);});this.pending.set(year,task);this.queue=task.catch(()=>{});return task;}
 private async request(url:string,outer:AbortSignal){outer.throwIfAborted();const local=new AbortController();let rejectAbort:()=>void=()=>{};const canceled=new Promise<never>((_,reject)=>{rejectAbort=()=>{local.abort();reject(new DOMException('Canceled','AbortError'));};});outer.addEventListener('abort',rejectAbort,{once:true});let timer:ReturnType<typeof setTimeout>|undefined;const timeout=new Promise<never>((_,reject)=>{timer=setTimeout(()=>{local.abort();reject(Error('请求超时。'));},this.timeout);});const work=(async()=>{const response=await this.fetcher(url,{signal:local.signal,method:'GET',headers:{Accept:'application/json'},credentials:'omit',redirect:'error',referrerPolicy:'no-referrer'});if(!response.ok||Number(response.headers.get('content-length'))>128*1024||/html/i.test(response.headers.get('content-type')||''))throw Error('没有取得年度 JSON。');const text=await response.text();if(text.length>128*1024)throw Error('年度数据过大。');return JSON.parse(text);})();try{return await Promise.race([work,canceled,timeout]);}finally{clearTimeout(timer);outer.removeEventListener('abort',rejectAbort);}}
}
