"""Secure-origin runtime regression against the APK's own web bundle.
Only synthetic data and a strict native-network fixture are used. CSP is unchanged.
"""
import json,pathlib,shutil,threading,http.server,functools,traceback,time,sys
from playwright.sync_api import sync_playwright
out=pathlib.Path('work/check205/browser');out.mkdir(parents=True,exist_ok=True)
site=pathlib.Path('work/site205');shutil.copytree('work/mobile-web',site,dirs_exist_ok=True)
shutil.copy('work/harness205/harness205.js',site/'harness205.js')
server=http.server.ThreadingHTTPServer(('127.0.0.1',4173),functools.partial(http.server.SimpleHTTPRequestHandler,directory=str(site)))
threading.Thread(target=server.serve_forever,daemon=True).start()
results=[]
def record(name,ok,detail=None):
 results.append({'name':name,'passed':bool(ok),'detail':detail});(out/'results.json').write_text(json.dumps(results,ensure_ascii=False,indent=2));print(('PASS ' if ok else 'FAIL ')+name,flush=True)
 if not ok:raise AssertionError(name)
BASE={'name':'测试','since':'2024-01-01','messages':[{'who':'me' if i%2==0 else 'luke','text':('我喜欢茉莉花。' if i==0 else '日常记录'+str(i)),'at':'2026-09-15T03:00:00Z'} for i in range(350)],'tasks':[],'notes':[],'checks':[],'memoryArchive':{'version':1,'autoRevision':1,'enabled':False,'chapters':[],'facts':[]}}
INIT=r'''({data,model,appearance})=>{
 if(!localStorage.getItem('luke-test205-seeded')){
 localStorage.setItem('luke-companion-v1',JSON.stringify(data));localStorage.setItem('luke-appearance-v1',JSON.stringify(appearance||{season:'autumn',period:'正午',effects:true}));localStorage.setItem('luke-backup-confirmed',String(Date.now()));if(model)localStorage.setItem('luke-model-credentials-v1',JSON.stringify({baseUrl:'https://memory-fixture.invalid/v1',model:'fixture',key:'synthetic-not-a-real-key'}));localStorage.setItem('luke-test205-seeded','yes');}
 const f={requests:[],cancelled:[],failures:0,hold:false,pending:[]};window.__fixture205=f;
 function reply(id,text,stream=false,status=200){const body=JSON.stringify({choices:[{message:{content:text},finish_reason:'stop'}]});if(stream)window.__lukeStreaming?.(id,status,'application/json',body,true);else window.__lukeNetwork?.(id,status,body);}
 function request(id,url,method,headers,body,stream=false){
 if(url.startsWith('https://api.open-meteo.com/')){queueMicrotask(()=>window.__lukeNetwork?.(id,200,JSON.stringify({utc_offset_seconds:28800,current:{time:Math.floor(Date.now()/1000),weather_code:0,temperature_2m:26},daily:{time:Array.from({length:7},(_,i)=>1789401600+i*86400),weather_code:Array(7).fill(0),temperature_2m_max:Array(7).fill(28)}})));return;}
 if(url!=='https://memory-fixture.invalid/v1/chat/completions'){queueMicrotask(()=>window.__lukeNetwork?.(id,503,'{}'));return;}
 const payload=JSON.parse(body),archive=payload.messages.some(m=>typeof m.content==='string'&&m.content.includes('你是聊天记忆整理器'));
 if(!archive&&!stream){queueMicrotask(()=>reply(id,'unrelated fixture request',false,503));return;}
 f.requests.push({archive,stream,payload});
 if(archive){if(f.hold){f.pending.push(id);return;}if(f.failures-->0){queueMicrotask(()=>reply(id,'fixture failure',false,503));return;}const p=JSON.parse(payload.messages.at(-1).content),source=p.records.find(m=>m.who==='me');queueMicrotask(()=>reply(id,JSON.stringify({summary:'本段保留了用户明确讲述的日常。',facts:source?[{key:'用户偏好',value:source.text,quote:source.text.slice(0,120),sourceIndex:source.index}]:[]})));}else queueMicrotask(()=>reply(id,'收到，我们把这件事好好记下来。',true));}
 window.LukeAndroid={request:(...args)=>request(...args,false),requestStream:(...args)=>request(...args,true),cancel:id=>f.cancelled.push(id),pageReady(){},systemTheme(){},haptic(){}};
}'''
def seeded(context,data=BASE,model=False):
 context.add_init_script('('+INIT+')('+json.dumps({'data':data,'model':model},ensure_ascii=False)+');')
 page=context.new_page();errors=[];page.on('pageerror',lambda e:errors.append(str(e)));page.goto('http://127.0.0.1:4173',wait_until='networkidle');page.get_by_role('tab',name='悄悄话',exact=True).wait_for();page.wait_for_timeout(400);return page,errors
def harness(page):page.evaluate("async()=>{window.H=await import('/harness205.js')}")
def settings(page,section=None):
 page.get_by_role('tab',name='回到身边',exact=True).click();page.locator('main > header.page-bar').get_by_role('button',name='打开设置',exact=True).click();page.get_by_role('heading',name='设置',exact=True).wait_for()
 if section:page.get_by_role('tab',name=section,exact=True).click()
def close(page):page.locator('.settings [data-slot=dialog-close]').click();page.locator('.settings').wait_for(state='detached')
def bounds_clear(page):return page.evaluate('''()=>[...document.querySelectorAll('.calendar-grid button,.date-grid button')].every(b=>{const i=b.querySelector('i');if(!i)return true;const main=b.querySelector('.calendar-day-main')||b.querySelector('span:last-child'),a=i.getBoundingClientRect(),c=main.getBoundingClientRect();return a.bottom<=c.top+.6||a.right<=c.left+.6||a.left>=c.right-.6})''')
try:
 with sync_playwright() as p:
  browser=p.chromium.launch(headless=True)
  context=browser.new_context(viewport={'width':393,'height':851},is_mobile=True,has_touch=True,locale='zh-CN',timezone_id='Asia/Shanghai');page,errors=seeded(context);harness(page)
  record('APK HTML retains restrictive network CSP',"connect-src 'none'" in page.locator('meta[http-equiv="Content-Security-Policy"]').get_attribute('content'))
  record('home has exactly one settings icon',page.get_by_role('button',name='打开设置',exact=True).count()==1)
  settings(page);page.get_by_role('textbox',name='搜索设置',exact=True).fill('气泡');record('settings search filters to matching entry',page.get_by_role('tab',name='头像与聊天样式',exact=True).count()==1 and page.get_by_role('tab',name='天气与位置',exact=True).count()==0)
  page.get_by_role('tab',name='头像与聊天样式',exact=True).click();head=page.locator('.settings-fixed-head').bounding_box();page.locator('.settings [data-slot=dialog-scroll-body]').evaluate('(e)=>e.scrollTop=e.scrollHeight');page.wait_for_timeout(250);after=page.locator('.settings-fixed-head').bounding_box();record('subpage header does not move when content scrolls',abs(head['y']-after['y'])<.5)
  page.get_by_role('button',name='返回设置目录',exact=True).click();record('search is preserved when returning to settings directory',page.get_by_role('textbox',name='搜索设置',exact=True).input_value()=='气泡');page.get_by_role('button',name='清除设置搜索',exact=True).click()
  page.get_by_role('tab',name='头像与聊天样式',exact=True).click()
  page.get_by_role('button',name='蜂蜜吐司头像',exact=True).click();page.locator('input[aria-label="选择我的头像"]').set_input_files('public/images/companions/cat.webp');page.wait_for_function("JSON.parse(localStorage.getItem('luke-display-v205')).avatar.startsWith('data:image/')")
  record('user photo is cropped and stored as a bounded local image',page.evaluate("JSON.parse(localStorage.getItem('luke-display-v205')).avatar.length<300000"));page.get_by_role('button',name='夏彦吐司头像',exact=True).click()
  for name,skin in [('暖茶','tea'),('向阳','sunflower'),('心意','hearts'),('四季','plain')]:
   page.get_by_role('button',name='气泡：'+name,exact=True).click();close(page);page.get_by_role('tab',name='悄悄话',exact=True).click();record('selectable bubble '+skin,page.locator('.bubble-frame').first.get_attribute('data-skin')==skin);page.screenshot(path=str(out/('chat-'+skin+'.png')));settings(page,'头像与聊天样式')
  close(page);page.get_by_role('tab',name='悄悄话',exact=True).click();record('chat mounts at most eighty history rows',page.locator('[data-message-index]').count()==80);record('both participants have image avatars',page.locator('.message.mine>.chat-avatar').count()>0 and page.locator('.message:not(.mine)>.chat-avatar').count()>0)
  page.get_by_role('button',name='更早的聊天',exact=True).click();record('older history remains accessible',int(page.locator('[data-message-index]').first.get_attribute('data-message-index'))<270);page.get_by_role('button',name='后面的聊天',exact=True).click();page.get_by_role('button',name='搜索聊天记录',exact=True).click();page.get_by_role('textbox',name='搜索聊天内容',exact=True).fill('日常');record('large search is paged rather than mounting every record',page.locator('.search-result').count()==100);page.get_by_role('button',name='继续查看结果',exact=False).click();record('search can load the next hundred matches',page.locator('.search-result').count()==200)
  page.get_by_role('button',name='返回聊天',exact=True).click();page.locator('.message-edit').first.click();record('correction has explicit cancel and does not truncate later history',page.get_by_role('button',name='取消更正',exact=True).is_visible() and page.evaluate("JSON.parse(localStorage.getItem('luke-companion-v1')).messages.length")==350);page.get_by_role('button',name='取消更正',exact=True).click()
  # Real touch gestures, not synthetic click dispatch.
  page.get_by_role('tab',name='回到身边',exact=True).click();cdp=context.new_cdp_session(page);page.evaluate('window.scrollTo(0,0)')
  for event,x in [('touchStart',275),('touchMove',245),('touchMove',180),('touchMove',105),('touchEnd',105)]:
   cdp.send('Input.dispatchTouchEvent',{'type':event,'touchPoints':[] if event=='touchEnd' else [{'x':x,'y':35}]});page.wait_for_timeout(35)
  page.wait_for_timeout(350);record('horizontal touch swipe switches bottom page',page.get_by_role('tab',name='悄悄话',exact=True).get_attribute('aria-selected')=='true')
  # Typography persists, independently from chat size.
  settings(page,'外观与字号');page.get_by_role('slider',name='全局字号',exact=True).focus();page.get_by_role('slider',name='全局字号',exact=True).press('End');page.get_by_role('slider',name='聊天字号',exact=True).focus();page.get_by_role('slider',name='聊天字号',exact=True).press('End');record('font controls update root and independent chat variables',page.evaluate("getComputedStyle(document.documentElement).fontSize==='20.8px'&&document.documentElement.style.getPropertyValue('--chat-font-size')==='24px'"))
  colors={}
  for season,label in [('spring','春'),('summer','夏'),('autumn','秋'),('winter','冬')]:
   for period in ['正午','深夜']:
    page.get_by_role('button',name=label,exact=True).click();page.get_by_role('button',name=period,exact=True).click();page.wait_for_function("([s,n])=>document.documentElement.dataset.season===s&&document.documentElement.dataset.night===n",arg=[season,'true' if period=='深夜' else 'false']);page.wait_for_timeout(400)
    palette=page.evaluate("()=>({root:getComputedStyle(document.documentElement).getPropertyValue('--scene-paper').trim(),dialog:getComputedStyle(document.querySelector('.settings')).getPropertyValue('--scene-paper').trim(),accent:getComputedStyle(document.documentElement).getPropertyValue('--season-accent').trim()})");record(season+' '+period+' settings inherits the active root theme',palette['root']==palette['dialog']);colors[season+period]=palette;page.screenshot(path=str(out/('theme-'+season+('-night' if period=='深夜' else '-day')+'.png')))
  record('season changes produce distinct accent palettes',len(set(v['accent'] for v in colors.values()))>=4)
  close(page);page.get_by_role('tab',name='一起计划',exact=True).click()
  for width in [320,360,393,430]:
   page.set_viewport_size({'width':width,'height':851});page.wait_for_timeout(250);record(str(width)+'px calendar has no work/rest date overlap at largest global font',bounds_clear(page));record(str(width)+'px calendar stays within viewport',page.locator('.calendar-grid').evaluate('(e)=>e.getBoundingClientRect().right<=innerWidth+1'));today=page.locator('.calendar-grid button[aria-current=date]');record(str(width)+'px today is a square avatar cell',today.count()==1 and today.locator('img').count()==1 and today.locator('.calendar-day-number').count()==0 and today.evaluate('(e)=>Math.abs(e.getBoundingClientRect().width-e.getBoundingClientRect().height)<1'))
  page.set_viewport_size({'width':393,'height':851});page.get_by_role('button',name='跳转到指定日期',exact=True).click();page.get_by_role('textbox',name='输入指定日期',exact=True).fill('2026-10-10');page.get_by_role('button',name='确定日期',exact=True).click();record('date jump opens target month and selects the make-up workday',page.locator('.calendar-grid button[aria-pressed=true]').get_attribute('aria-label').startswith('2026-10-10') and page.locator('.calendar-grid button[aria-pressed=true] i').inner_text()=='班');record('October holiday badges do not overlap dates',bounds_clear(page));page.screenshot(path=str(out/'calendar.png'))
  page.get_by_role('tab',name='计时',exact=True).click();page.get_by_role('button',name='开始计时',exact=True).click();page.wait_for_timeout(1600);record('study clock activates the lightweight character pendant',page.locator('.focus-keepsake').get_attribute('data-playing')=='true');page.emulate_media(reduced_motion='reduce');record('reduced-motion disables pendant animation',page.locator('.focus-keepsake-pendant').evaluate('(e)=>getComputedStyle(e).animationName')=='none');page.emulate_media(reduced_motion='no-preference');page.get_by_role('button',name='结束并保存',exact=True).click();page.wait_for_timeout(200);record('timer saves exactly one completed record',page.evaluate("JSON.parse(localStorage.getItem('luke-companion-v1')).focusLog.length")==1)
  page.reload(wait_until='networkidle');harness(page);record('avatar and font preferences survive restart',page.evaluate("document.documentElement.style.fontSize==='20.8px'&&JSON.parse(localStorage.getItem('luke-display-v205')).avatar.startsWith('data:image/')"))
  record('no uncaught runtime errors in the integrated UI',not errors,errors)
  # Actual IndexedDB transactions; the fixture never replaces browser storage APIs.
  storage=browser.new_context();sp=storage.new_page();sp.goto('http://127.0.0.1:4173/harness205.js');harness(sp)
  checks=sp.evaluate('''async()=>{const results=[],test=(name,ok)=>results.push({name,passed:!!ok});const initial={name:'存储测试',since:'2024-01-01',messages:[{who:'me',text:'旧约定'},{who:'luke',text:'记住了'}],tasks:[],notes:[],checks:[]};localStorage.setItem('luke-companion-v1',JSON.stringify(initial));let old=await H.loadDurable(initial);test('legacy main data migrates into actual IndexedDB',old.backend==='indexeddb'&&old.data.messages.length===2);const newer={...old.data,name:'更新后的称呼',messages:[...old.data.messages,{who:'me',text:'新约定'}]};let current=await H.saveDurable(newer,old);localStorage.setItem('luke-companion-v1',JSON.stringify(initial));localStorage.removeItem(H.STORE_MARKER);let reloaded=await H.loadDurable(initial);test('stale localStorage cannot replace a newer IndexedDB snapshot',reloaded.data.name===newer.name&&reloaded.data.messages.length===3);let conflicted=false;try{await H.saveDurable({...initial,name:'过时页面'},old)}catch{conflicted=true}test('compare-and-swap refuses an obsolete page write',conflicted);localStorage.setItem('luke-model-credentials-v1','private-fixture');localStorage.setItem('luke-display-v205',JSON.stringify({scale:1.2}));const backup=H.parseFullBackup(H.stringifyFullBackup(reloaded.data));test('complete backup uses authoritative history and excludes model credentials',JSON.parse(backup.storage['luke-companion-v1']).messages.length===3&&!('luke-model-credentials-v1' in backup.storage));const restored=await H.replaceDurable({...initial,name:'备份恢复'}, {'luke-display-v205':JSON.stringify({scale:1.1})});test('restore atomically replaces main data and nonsensitive settings',restored.data.name==='备份恢复'&&JSON.parse(localStorage.getItem('luke-display-v205')).scale===1.1&&localStorage.getItem('luke-model-credentials-v1')==='private-fixture');const proto=Storage.prototype,set=proto.setItem;proto.setItem=function(k,v){if(k==='luke-display-v205'&&v.includes('quota-fixture'))throw new DOMException('fixture quota','QuotaExceededError');return set.call(this,k,v)};let failed=false;try{await H.replaceDurable({...initial,name:'不应生效'}, {'luke-display-v205':'quota-fixture'})}catch{failed=true}finally{proto.setItem=set}const after=await H.loadDurable(initial);test('failed settings restore rolls back and leaves authoritative chat intact',failed&&after.data.name==='备份恢复'&&JSON.parse(localStorage.getItem('luke-display-v205')).scale===1.1);return results}''')
  for item in checks:record(item['name'],item['passed'])
  storage.close()
  # Default migration, automatic retry, fact extraction, reload and resume.
  auto=browser.new_context(viewport={'width':393,'height':851},is_mobile=True,has_touch=True,locale='zh-CN',timezone_id='Asia/Shanghai');small={**BASE,'messages':BASE['messages'][:4]};small['memoryArchive']={'version':1,'enabled':False,'chapters':[]}
  ap,ae=seeded(auto,small,True);harness(ap);ap.evaluate('window.__fixture205.failures=1')
  ap.wait_for_function("window.__fixture205.requests.some(r=>r.archive)",timeout=15000);ap.wait_for_function("JSON.parse(localStorage.getItem('luke-memory-retry-v205')||'null')?.attempt===1",timeout=10000);record('automatic memory starts without manual enable or summarize action',ap.evaluate("JSON.parse(localStorage.getItem('luke-companion-v1')).memoryArchive.enabled"));ap.reload(wait_until='networkidle');harness(ap)
  ap.wait_for_function("JSON.parse(localStorage.getItem('luke-companion-v1')).memoryArchive.facts?.length>0",timeout=40000);record('failed automatic extraction retries after restart without losing the cursor',ap.evaluate("JSON.parse(localStorage.getItem('luke-companion-v1')).memoryArchive.chapters.at(-1).to===4"))
  ap.get_by_role('tab',name='悄悄话',exact=True).click();ap.get_by_role('textbox',name='发送给夏彦的消息',exact=True).fill('我现在更喜欢桂花。');ap.get_by_role('button',name='发送消息',exact=True).click();ap.wait_for_function("JSON.parse(localStorage.getItem('luke-companion-v1')).messages.length===6",timeout=10000);ap.wait_for_function("JSON.parse(localStorage.getItem('luke-companion-v1')).memoryArchive.chapters.at(-1).to===6",timeout=25000);record('new completed chats append automatic chapters without deleting originals',ap.evaluate("JSON.parse(localStorage.getItem('luke-companion-v1')).messages[0].text==='我喜欢茉莉花。'"));record('ordinary chat includes the extracted fact ledger',ap.evaluate("window.__fixture205.requests.some(r=>r.stream&&JSON.stringify(r.payload).includes('rememberedFacts'))"));record('automatic pipeline has no uncaught errors',not ae,ae)
  ap.evaluate('window.__fixture205.hold=true');ap.get_by_role('textbox',name='发送给夏彦的消息',exact=True).fill('再记一件新的事。');ap.get_by_role('button',name='发送消息',exact=True).click();ap.wait_for_function('window.__fixture205.pending.length>0',timeout=25000);settings(ap,'长期聊天记忆');ap.get_by_role('switch',name='自动整理长期记忆',exact=True).uncheck();ap.wait_for_timeout(300);record('manual intervention cancels an in-flight automatic task',ap.evaluate('window.__fixture205.cancelled.length>0'));ap.evaluate('''()=>{const id=window.__fixture205.pending[0];window.__lukeNetwork?.(id,200,JSON.stringify({choices:[{message:{content:JSON.stringify({summary:'late stale result',facts:[]})},finish_reason:'stop'}]}))}''');ap.wait_for_timeout(300);record('late canceled extraction cannot overwrite newer settings or cursor',ap.evaluate("JSON.parse(localStorage.getItem('luke-companion-v1')).memoryArchive.enabled===false&&JSON.parse(localStorage.getItem('luke-companion-v1')).memoryArchive.chapters.at(-1).to===6"))
  auto.close();context.close();browser.close()
except Exception as e:
 results.append({'name':'runtime suite completion','passed':False,'detail':str(e)});(out/'failure.txt').write_text(traceback.format_exc());print(traceback.format_exc())
 try:page.screenshot(path=str(out/'failure.png'))
 except:pass
finally:
 (out/'results.json').write_text(json.dumps(results,ensure_ascii=False,indent=2));server.shutdown()
sys.exit(0 if results and all(r['passed'] for r in results) else 1)
