import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DISPLAY_KEY,LEGACY_DISPLAY_KEY,DEFAULT_DISPLAY,COMPANIONS,parseDisplay,readDisplay,saveDisplay} from '../../lib/display-preferences.ts';
class MemoryStorage{map=new Map();fail=false;getItem(k){return this.map.get(k)??null;}setItem(k,v){if(this.fail)throw Error('synthetic quota failure');this.map.set(k,v);}}
function setup(){const s=new MemoryStorage();globalThis.localStorage=s;globalThis.document={documentElement:{style:{fontSize:'',values:new Map(),setProperty(k,v){this.values.set(k,v)}},dataset:{}}};globalThis.window=new EventTarget();return s;}
test('new defaults use 95 percent and 13px, not a misleading release version',()=>{assert.equal(DEFAULT_DISPLAY.scale,.95);assert.equal(DEFAULT_DISPLAY.chatSize,13);assert.equal(JSON.parse(fs.readFileSync('package.json')).version,'2.0.10');});
test('a complete 2.0.9-style v206 record wins over stale v205 values',()=>{const s=setup();s.setItem(LEGACY_DISPLAY_KEY,JSON.stringify({version:1,scale:1,chatSize:16,bubble:'tea',avatar:COMPANIONS.dog}));s.setItem(DISPLAY_KEY,JSON.stringify({version:2,scale:1.2,chatSize:22,bubbleMine:'plain',bubbleLuke:'sunflower',avatarMine:COMPANIONS.toast,avatarLuke:COMPANIONS.dog}));const p=readDisplay();assert.equal(p.scale,1.2);assert.equal(p.chatSize,22);assert.equal(p.bubbleMine,'plain');assert.equal(p.bubbleLuke,'sunflower');assert.equal(p.avatarLuke,COMPANIONS.dog);});
test('reading a legacy record does not eagerly write or delete it',()=>{const s=setup(),raw=JSON.stringify({version:1,bubble:'hearts',avatar:COMPANIONS.toast,lukeAvatar:'toast',scale:1.15,chatSize:16});s.setItem(LEGACY_DISPLAY_KEY,raw);const p=readDisplay();assert.equal(p.bubbleMine,'hearts');assert.equal(p.bubbleLuke,'hearts');assert.equal(p.avatarMine,COMPANIONS.toast);assert.equal(p.avatarLuke,COMPANIONS.toast);assert.equal(s.getItem(DISPLAY_KEY),null);assert.equal(s.getItem(LEGACY_DISPLAY_KEY),raw);});
test('first user save preserves legacy backup and unrecognized newer preference fields',()=>{const s=setup();s.setItem(DISPLAY_KEY,JSON.stringify({version:2,scale:1.1,chatSize:19,extraSetting:{keep:true}}));s.setItem(LEGACY_DISPLAY_KEY,'original snapshot');saveDisplay({...readDisplay(),bubbleMine:'hearts'});assert.deepEqual(JSON.parse(s.getItem(DISPLAY_KEY)).extraSetting,{keep:true});assert.equal(s.getItem(LEGACY_DISPLAY_KEY),'original snapshot');});
test('one participant changing the bubble cannot overwrite the other',()=>{setup();const p=saveDisplay({...DEFAULT_DISPLAY,bubbleMine:'hearts',bubbleLuke:'sunflower'});saveDisplay({...p,bubbleMine:'plain'});assert.equal(readDisplay().bubbleLuke,'sunflower');});
test('both participants can retain an uploaded avatar, independently',()=>{setup();const photo='data:image/png;base64,aGVsbG8=';saveDisplay({...DEFAULT_DISPLAY,avatarMine:photo,avatarLuke:COMPANIONS.toast});assert.equal(readDisplay().avatarMine,photo);saveDisplay({...readDisplay(),avatarLuke:photo});assert.equal(readDisplay().avatarMine,photo);assert.equal(readDisplay().avatarLuke,photo);});
test('existing explicit text sizes remain unchanged within supported bounds',()=>{for(const size of [13,16,18,24]){assert.equal(parseDisplay({chatSize:size}).chatSize,size);}assert.equal(parseDisplay({scale:1.3}).scale,1.3);});
test('range supports 75 to 160 percent and 10 to 32px, clamps only invalid extremes',()=>{const p=parseDisplay({scale:.75,chatSize:10});assert.equal(p.scale,.75);assert.equal(p.chatSize,10);assert.equal(parseDisplay({scale:1.6,chatSize:32}).scale,1.6);assert.equal(parseDisplay({scale:2,chatSize:100}).chatSize,32);assert.equal(parseDisplay({scale:-5,chatSize:-10}).scale,.75);});
test('NaN and Infinity use finite defaults',()=>{assert.equal(parseDisplay({scale:NaN,chatSize:Infinity}).scale,.95);assert.equal(parseDisplay({scale:Infinity,chatSize:NaN}).chatSize,13);});
for(const bad of ['not json','null','[]','42','{"version":999,"scale":1.2}'])test('unreadable or future settings are not silently destroyed: '+bad,()=>{const s=setup();s.setItem(DISPLAY_KEY,bad);assert.throws(()=>readDisplay());assert.throws(()=>saveDisplay(DEFAULT_DISPLAY));assert.equal(s.getItem(DISPLAY_KEY),bad);});
test('storage quota failure does not publish visual state or success event',()=>{const s=setup();s.setItem(DISPLAY_KEY,JSON.stringify(DEFAULT_DISPLAY));s.fail=true;let events=0;window.addEventListener('luke-display-change',()=>events++);assert.throws(()=>saveDisplay({...readDisplay(),scale:1.4}));assert.equal(readDisplay().scale,.95);assert.equal(document.documentElement.style.fontSize,'');assert.equal(events,0);});
test('successful save publishes the actually persisted state',()=>{setup();let event=0;window.addEventListener('luke-display-change',()=>event++);saveDisplay({...DEFAULT_DISPLAY,scale:1.5,chatSize:30});assert.equal(document.documentElement.style.fontSize,'24px');assert.equal(document.documentElement.style.values.get('--chat-font-size'),'30px');assert.equal(event,1);assert.equal(readDisplay().chatSize,30);});
test('custom image resource names from a newer build are retained, not rewritten',()=>{setup();const a='/images/details206/luke-glasses.webp';assert.equal(parseDisplay({avatarLuke:a}).avatarLuke,a);});
test('unsafe avatar URL falls back without remote fetch',()=>{assert.equal(parseDisplay({avatarLuke:'https://thirdparty.invalid/avatar.png'}).avatarLuke,COMPANIONS.cat);assert.equal(parseDisplay({avatarMine:'data:image/svg+xml;base64,aA=='}).avatarMine,COMPANIONS.dog);});
test('layout uses separate bubbles for live output and each message',()=>{const s=fs.readFileSync('app/page.tsx','utf8');assert.ok(s.includes("<ChatBubble mine={m.who==='me'} preferences={display}>"));assert.ok(s.includes('<ChatBubble preferences={display}>{liveReply?'));assert.ok(s.includes('const avatar=<ChatAvatar mine={false}'));assert.ok(!s.includes('data-skin={display.bubble}'));});
test('avatar decoding cancellation is handled on target switch, reset and unmount',()=>{const s=fs.readFileSync('components/chat-appearance.tsx','utf8');assert.match(s,/target=side/);assert.match(s,/selection.current===controller/);assert.match(s,/cancel\(\);setNotice\(''\);setSide\(v\)/);assert.match(s,/key={src}/);});
