"""Real pointer / DOM continuity checks on the exact built application."""

def verify_companion_theme(page, check, traces, out):
    page.set_viewport_size({'width':390,'height':844})
    page.emulate_media(reduced_motion='no-preference')
    page.get_by_role('tab',name='回到身边',exact=True).click()
    page.locator('.luke-desk').wait_for()
    page.get_by_role('button',name='打开设置',exact=True).first.click()
    page.get_by_role('tab',name='四季与昼夜',exact=True).click()
    page.get_by_role('button',name='春',exact=True).click();page.get_by_role('button',name='正午',exact=True).click()
    page.wait_for_timeout(600);page.locator('.settings').get_by_role('button',name='关闭',exact=True).click();page.wait_for_timeout(1200)
    page.get_by_role('button',name='查看第 1 张照片',exact=True).click();page.wait_for_timeout(1100)
    before=page.locator('.luke-note p').inner_text()
    page.get_by_role('button',name='换一张夏彦便笺',exact=True).click()
    check('Luke note changes only on intentional request',page.locator('.luke-note p').inner_text()!=before)
    page.get_by_role('button',name='下一张照片',exact=True).click()
    page.wait_for_timeout(1100)
    check('gallery next accepts real pointer without the image intercepting',page.locator('.photo-dots [aria-current=true]').get_attribute('aria-label')=='查看第 2 张照片')
    for word,season in [('夏','summer'),('秋','autumn'),('冬','winter'),('春','spring')]:
        page.get_by_role('button',name='打开设置',exact=True).first.click()
        page.get_by_role('tab',name='四季与昼夜',exact=True).click()
        page.get_by_role('button',name=word,exact=True).click()
        page.get_by_role('button',name='正午',exact=True).click()
        page.wait_for_timeout(650)
        page.evaluate('''()=>{const start=performance.now(),home=document.querySelector('.home-grid'),card=document.querySelector('.quote-card'),img=document.querySelector('.hero-slide img');window.__themeFrames=[];
         function sample(){const c=document.querySelector('.hero-season-cover');const active=document.querySelector('.photo-dots [aria-current=true]');const index=Number(active?.getAttribute('aria-label')?.match(/\\d+/)?.[0]??1)-1;const photo=document.querySelectorAll('.hero-slide img')[index];const style=getComputedStyle(card);window.__themeFrames.push({t:performance.now()-start,season:document.documentElement.dataset.season,modal:!!document.querySelector('.settings'),homeStable:home===document.querySelector('.home-grid'),imageStable:img===document.querySelector('.hero-slide img'),opacity:style.opacity,bg:style.backgroundColor,gradient:style.backgroundImage,cover:c?Number(getComputedStyle(c).opacity):0,covered:c?.complete&&c.naturalWidth>0,decoded:photo?.complete&&photo.naturalWidth>0,pos:getComputedStyle(img).objectPosition,album:document.querySelector('.hero-gallery').dataset.albumSeason,index});if(performance.now()-start<1700)requestAnimationFrame(sample)}sample()}''')
        page.locator('.settings').get_by_role('button',name='关闭',exact=True).click()
        page.wait_for_timeout(1800)
        frames=page.evaluate('window.__themeFrames');traces['home-palette-'+season]=frames
        check(f'{season}: home and first slide retain DOM identity',all(f['homeStable'] and f['imageStable'] for f in frames))
        check(f'{season}: root theme waits for the settings exit',all(not f['modal'] or f['season']!=season for f in frames))
        check(f'{season}: card stays opaque with no discrete gradient',all(f['opacity']=='1' and f['gradient']=='none' for f in frames))
        check(f'{season}: solid card colour has intermediate states',len({f['bg'] for f in frames})>=5)
        check(f'{season}: no unprepared photograph is exposed',all(f['decoded'] or f['covered'] and f['cover']>=.99 for f in frames))
        check(f'{season}: album settles and retains selected index',frames[-1]['album']==season and frames[-1]['index']==1 and frames[-1]['cover']==0)
    # A sixth winter image must clamp to the fourth autumn image, not jump to one.
    page.get_by_role('button',name='打开设置',exact=True).first.click();page.get_by_role('tab',name='四季与昼夜',exact=True).click()
    page.get_by_role('button',name='冬',exact=True).click();page.wait_for_timeout(600)
    page.locator('.settings').get_by_role('button',name='关闭',exact=True).click();page.wait_for_timeout(1100)
    page.get_by_role('button',name='查看第 6 张照片',exact=True).click();page.wait_for_timeout(1100)
    page.get_by_role('button',name='打开设置',exact=True).first.click();page.get_by_role('tab',name='四季与昼夜',exact=True).click()
    page.get_by_role('button',name='秋',exact=True).click();page.wait_for_timeout(600)
    page.locator('.settings').get_by_role('button',name='关闭',exact=True).click();page.wait_for_timeout(1100)
    check('shorter album clamps to its final image',page.locator('.photo-dots [aria-current=true]').get_attribute('aria-label')=='查看第 4 张照片')
    page.get_by_role('button',name='接一份专注委托').click();page.locator('.study-timer').wait_for()
    check('home companion shortcut opens the existing study feature',page.locator('.study-companion-note').count()==1)
    before=page.locator('.luke-stamp-grid [data-recorded=true]').count()
    page.locator('.luke-subject-chips').get_by_role('button',name='英语',exact=True).click()
    page.get_by_role('button',name='开始计时',exact=True).click();page.wait_for_timeout(1250)
    check('study clock advances and subject remains selected',page.locator('.luke-study-dial .focus-clock').inner_text()!='00:00:00' and '英语' in page.locator('.luke-dial-caption').inner_text())
    check('running study does not fabricate a saved calendar stamp',page.locator('.luke-stamp-grid [data-recorded=true]').count()==before)
    check('running subject chips are disabled',page.locator('.luke-subject-chips button:enabled').count()==0)
    page.get_by_role('tab',name='回到身边',exact=True).click();page.get_by_role('button',name='接一份专注委托').click()
    check('navigation preserves the running study',page.get_by_role('button',name='结束并保存',exact=True).count()==1)
    page.get_by_role('button',name='结束并保存',exact=True).click()
    check('saved study produces a real calendar stamp',page.locator('.luke-stamp-grid [data-recorded=true]').count()>=1)
    check('calendar never counts unlogged zero duration as a stamp',page.locator('.luke-stamp-grid [data-recorded=false] img').count()==0)
    for width,height in [(320,568),(390,844),(844,390),(768,1024)]:
        page.set_viewport_size({'width':width,'height':height});page.wait_for_timeout(200)
        check(f'companion study has no horizontal overflow {width}x{height}',page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
    page.set_viewport_size({'width':390,'height':844});page.screenshot(path=str(out/'luke-study.png'),full_page=True)
    page.get_by_role('tab',name='回到身边',exact=True).click();page.wait_for_timeout(400)
    page.screenshot(path=str(out/'luke-home.png'),full_page=True)
    page.get_by_role('button',name='收藏今天的线索').click();check('Luke desk opens notes without altering records',page.get_by_role('button',name='新建笔记',exact=True).count()>0)
    page.get_by_role('tab',name='回到身边',exact=True).click();page.get_by_role('button',name='和夏彦聊一会儿').click()
    check('Luke desk chat shortcut opens the existing conversation',page.locator('.chat-page .composer').count()==1)
