import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import crypto from 'node:crypto';
import {BUNDLED_HOLIDAYS,parseStaticHoliday,parseApiHoliday,holidayIndex,localHoliday,scheduleSignature} from '../../lib/holiday-data.ts';
import {HolidayRepository,HOLIDAY_CACHE,HOLIDAY_PREFS} from '../../lib/holiday-repository.ts';
const now=Date.parse('2026-09-18T01:00:00Z'),clone=v=>JSON.parse(JSON.stringify(v)),doc=BUNDLED_HOLIDAYS.find(d=>d.year===2026);
const later=()=>({...clone(doc),year:2027,days:doc.days.map(d=>({...d,date:d.date.replace('2026','2027')}))});
const api=()=>({code:0,holiday:Object.fromEntries(later().days.map(d=>[d.date.slice(5),{name:d.name,date:d.date,holiday:d.isOffDay,rest:123}]))});
class Store{map=new Map();fail=false;getItem(k){return this.map.get(k)??null}setItem(k,v){if(this.fail)throw Error('quota');this.map.set(k,v)}removeItem(k){this.map.delete(k)}}
const response=(v,status=200)=>new Response(JSON.stringify(v),{status,headers:{'content-type':'application/json'}});
function fixture(){let at=now,online=true,reply=async()=>response(later());const storage=new Store(),calls=[];const repo=new HolidayRepository(storage,async(url,init)=>{calls.push({url,init});return reply(url,init)},()=>at,()=>online,8);return {repo,storage,calls,reply(fn){reply=fn},advance(ms){at+=ms},offline(){online=false},online(){online=true},time(){return at}};}
for(const y of [2023,2024,2025,2026])test(`bundled year ${y} equals the known upstream Git blob`,()=>{const bytes=readFileSync(`data/holidays/${y}.json`),p=JSON.parse(readFileSync('data/holidays/provenance.json')).find(v=>v.year===y);assert.equal(crypto.createHash('sha1').update(`blob ${bytes.length}\0`).update(bytes).digest('hex'),p.upstreamGitBlobSha);assert.equal(parseStaticHoliday(JSON.parse(bytes),y).year,y);});
test('2026 contains 33 rest days and six compensatory work dates',()=>{assert.equal(doc.days.filter(d=>d.isOffDay).length,33);assert.equal(doc.days.filter(d=>!d.isOffDay).length,6);assert.equal(localHoliday('2026-10-10').kind,'work');assert.equal(localHoliday('2026-09-25').kind,'rest');});
test('2023 announcement previous December entry is partial prior-year coverage',()=>{const f=fixture();assert.equal(f.repo.snapshot(2022).complete,false);assert.equal(f.repo.snapshot(2022).days['2022-12-31'].kind,'rest');assert.equal(localHoliday('2024-06-08'),null);});
for(const [name,mutate] of Object.entries({wrongYear:d=>d.year=2028,empty:d=>d.days=[],partial:d=>d.days=d.days.slice(0,4),duplicate:d=>d.days.push(d.days[0]),nonBoolean:d=>d.days[0].isOffDay='false',invalidDate:d=>d.days[0].date='2027-02-31',badPaper:d=>d.papers=['https://gov.cn.evil.test/'],script:d=>d.days[0].name='<script>'}))test('static validation refuses '+name,()=>{const d=later();mutate(d);assert.throws(()=>parseStaticHoliday(d,2027));});
test('API holiday false is work, never determined by rest value',()=>{assert.equal(parseApiHoliday(api(),2027).days.find(d=>d.date==='2027-10-10').isOffDay,false);const d=api();d.holiday['01-01'].holiday='true';assert.throws(()=>parseApiHoliday(d,2027));});
test('first offline launch reads all four years without requests',async()=>{const f=fixture();f.offline();for(const y of [2023,2024,2025,2026]){await f.repo.refresh(y);assert.equal(f.repo.snapshot(y).complete,true);}assert.equal(f.calls.length,0);});
test('static success never calls fallback; requests include no user data',async()=>{const f=fixture();await f.repo.refresh(2027);assert.equal(f.calls.length,1);assert.equal(f.repo.snapshot(2027).origin,'static');const r=f.calls[0];assert.deepEqual(r.init.headers,{Accept:'application/json'});assert.equal(r.init.body,undefined);assert.equal(r.init.credentials,'omit');});
test('missing unknown year tries static then API once and persists full result',async()=>{const f=fixture();f.reply(async u=>u.includes('jsdelivr')?response({},404):response(api()));await f.repo.refresh(2027);assert.equal(f.calls.length,2);assert.equal(f.repo.snapshot(2027).origin,'api');assert.equal(f.repo.snapshot(2027).days['2027-10-10'].kind,'work');const cold=new HolidayRepository(f.storage,async()=>{throw Error('no network')},()=>now+7*86400000,()=>false);assert.equal(cold.snapshot(2027).complete,true);});
test('primary outage preserves existing reviewed year without downgrade',async()=>{const f=fixture();f.reply(async()=>response({},503));await f.repo.refresh(2026);assert.equal(f.calls.length,1);assert.equal(f.repo.snapshot(2026).origin,'bundled');});
test('static conflict cannot rewrite embedded dates',async()=>{const f=fixture(),wrong=clone(doc);wrong.days.find(d=>d.date==='2026-10-10').isOffDay=true;f.reply(async()=>response(wrong));await f.repo.refresh(2026);assert.equal(f.repo.snapshot(2026).days['2026-10-10'].kind,'work');assert.match(f.repo.snapshot(2026).message,/已校对/);});
test('malformed cached rows do not break bundled cold start',()=>{const f=fixture();f.storage.setItem(HOLIDAY_CACHE,'not json');f.repo.reload();assert.equal(f.repo.snapshot(2026).complete,true);});
test('20 simultaneous requests coalesce; successful refresh is throttled',async()=>{const f=fixture();await Promise.all(Array.from({length:20},()=>f.repo.refresh(2027)));assert.equal(f.calls.length,1);f.advance(2*86400000);await f.repo.refresh(2027);assert.equal(f.calls.length,1);f.advance(6*86400000);await f.repo.refresh(2027);assert.equal(f.calls.length,2);});
test('failures retry later, not on every component render',async()=>{const f=fixture();f.reply(async()=>response({},503));await f.repo.refresh(2027);await f.repo.refresh(2027,true);await f.repo.refresh(2027);assert.equal(f.calls.length,2);f.advance(60001);await f.repo.refresh(2027,true);assert.equal(f.calls.length,4);});
test('disabled automatic and fallback policy is honored without deleting cache',async()=>{const f=fixture();f.repo.setPolicy({autoUpdate:false,fallback:false});await f.repo.refresh(2027);assert.equal(f.calls.length,0);f.reply(async()=>response({},404));await f.repo.refresh(2027,true);assert.equal(f.calls.length,1);assert.equal(f.repo.snapshot(2027).complete,false);});
test('too-far future never requests or invents a schedule',async()=>{const f=fixture();await f.repo.refresh(2030,true);assert.equal(f.calls.length,0);assert.equal(f.repo.snapshot(2030).complete,false);});
test('quota failure keeps in-memory success and explains unsaved cache',async()=>{const f=fixture();f.storage.fail=true;await f.repo.refresh(2027);assert.equal(f.repo.snapshot(2027).complete,true);assert.match(f.repo.snapshot(2027).message,/缓存未能保存/);assert.throws(()=>f.repo.setPolicy({autoUpdate:false}));assert.equal(f.repo.settings.autoUpdate,true);});
test('abort even an uncooperative transport ignores late data and permits resume',async()=>{const f=fixture();let resolve;f.reply(()=>new Promise(r=>resolve=r));const job=f.repo.refresh(2027);await new Promise(r=>setTimeout(r,0));f.repo.cancel();await job;assert.equal(f.repo.snapshot(2027).complete,false);resolve(response(later()));await new Promise(r=>setTimeout(r,0));assert.equal(f.repo.snapshot(2027).complete,false);f.reply(async()=>response(later()));await f.repo.refresh(2027);assert.equal(f.repo.snapshot(2027).complete,true);});
test('hard timeout proceeds to fallback without waiting for transport forever',async()=>{const f=fixture();f.reply(u=>u.includes('jsdelivr')?new Promise(()=>{}):Promise.resolve(response(api())));await f.repo.refresh(2027);assert.equal(f.repo.snapshot(2027).origin,'api');});
test('reload reads external restored settings without replacing them first',async()=>{const f=fixture();await f.repo.refresh(2027);f.storage.removeItem(HOLIDAY_CACHE);f.storage.setItem(HOLIDAY_PREFS,JSON.stringify({autoUpdate:false,fallback:false}));f.repo.reload();assert.equal(f.repo.snapshot(2027).complete,false);assert.equal(f.storage.getItem(HOLIDAY_CACHE),null);assert.equal(f.repo.settings.autoUpdate,false);});
