import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createTransientDrafts} from '../../lib/transient-form.ts';
import {normalizeDateEntry,yearFromEntry,boundedMonth,moveCalendarDay} from '../../lib/date-interaction.ts';
import {parseCalendarDate} from '../../lib/china-holidays.ts';
const date=value=>parseCalendarDate(value);
const key=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
for(const [raw,wanted] of [['20260915','2026-09-15'],['2026/9/5','2026-09-05'],['2026.9.15','2026-09-15'],['２０２６０９１５','2026-09-15'],['2026-09-15','2026-09-15'],[' 2026/1/2 ','2026-01-02']])test('date entry '+raw,()=>assert.equal(normalizeDateEntry(raw),wanted));
for(const raw of ['2026-02-30','2026/13/5','202609','nonsense','2026-00-01'])test('invalid entry remains invalid '+raw,()=>assert.equal(parseCalendarDate(normalizeDateEntry(raw)),null));
for(const [raw,wanted] of [['2026',2026],['２０００',2000],['',null],['20',null],['1900',1900],['1899',null],['2101',null],['2e3',null]])test('year buffer '+raw,()=>assert.equal(yearFromEntry(raw,1900,2100),wanted));
for(const [from,pressed,shift,wanted] of [['2026-01-31','PageDown',false,'2026-02-28'],['2024-02-29','PageDown',true,'2025-02-28'],['2026-01-01','ArrowLeft',false,'2025-12-31'],['2026-09-20','Home',false,'2026-09-14'],['2026-09-14','End',false,'2026-09-20'],['2026-01-31','PageUp',false,'2025-12-31']])test('calendar keyboard '+from+' '+pressed,()=>assert.equal(key(moveCalendarDay(date(from),pressed,shift)),wanted));
test('unhandled calendar key has no side effects',()=>assert.equal(moveCalendarDay(date('2026-09-14'),'a'),null));
test('month navigation clamps both ends',()=>{assert.equal(key(boundedMonth(1899,0,date('1900-04-03'),date('2026-09-15'))),'1900-04-01');assert.equal(key(boundedMonth(2027,1,date('1900-04-03'),date('2026-09-15'))),'2026-09-01');});
test('draft restores without modifying original',()=>{const c=createTransientDrafts(),base={name:'a',key:'fixture-not-real'},value={...base,name:'b'};c.write('model',base,value);value.name='after';assert.equal(c.read('model',base).name,'b');assert.equal(base.name,'a');});
test('discard deletes pending settings',()=>{const c=createTransientDrafts();c.write('x',{a:1},{a:2});c.clear('x');assert.deepEqual(c.read('x',{a:1}),{a:1});});
test('changed persisted settings invalidate stale input',()=>{const c=createTransientDrafts();c.write('x',{a:1},{a:2});assert.deepEqual(c.read('x',{a:3}),{a:3});});
test('drafts for different forms remain separate',()=>{const c=createTransientDrafts();c.write('model',{v:1},{v:2});assert.deepEqual(c.read('weather',{v:3}),{v:3});});
test('unchanged form has no pending entry',()=>{const c=createTransientDrafts();c.write('x',{a:1},{a:2});c.write('x',{a:1},{a:1});assert.deepEqual(c.read('x',{a:1}),{a:1});});
test('old unsaved input expires instead of lingering indefinitely',()=>{let now=0;const c=createTransientDrafts(100,()=>now);c.write('x',{v:1},{v:2});now=101;assert.deepEqual(c.read('x',{v:1}),{v:1});});
const read=p=>readFileSync(new URL('../../'+p,import.meta.url),'utf8');
test('draft helper never writes to storage or the network',()=>assert.doesNotMatch(read('lib/transient-form.ts'),/localStorage|sessionStorage|fetch\(/));
test('cancel and editing invalidate the same model request',()=>{const s=read('components/connection-settings.tsx');assert.match(s,/取消连接测试/);assert.match(s,/task.current===controller/);assert.match(s,/cancel\(''\);draft.update/);});
test('weather save is not coupled to model credentials',()=>assert.match(read('components/connection-settings.tsx'),/connections.saveWeather\(weather\)/));
test('note choice locks before invoking any action',()=>assert.match(read('components/memo-actions.tsx'),/if\(choosing.current\|\|!open\)return;choosing.current=true/));
test('date picker restores focus to its trigger',()=>assert.match(read('components/date-field.tsx'),/finalFocus=\{trigger\}/));
