"""Verify safe focus and rendering contracts with actual DOM controls."""

def verify_memo_focus(page, check):
    page.emulate_media(reduced_motion='no-preference')
    page.set_viewport_size({'width':390,'height':844})
    page.get_by_role('tab', name='时光手记', exact=True).click()
    more=page.get_by_role('button',name='手记操作：交互回归测试专用手记',exact=True)
    more.scroll_into_view_if_needed();more.click()
    sheet=page.locator('[data-memo-actions=true]');sheet.wait_for()
    sheet.get_by_role('button',name='移到回收站',exact=True).click()
    safe=sheet.get_by_role('button',name='保留手记',exact=True)
    check('trash confirmation initially focuses the safe action',safe.evaluate('(node)=>node===document.activeElement'))
    page.keyboard.press('Enter')
    target=sheet.get_by_role('button',name='移到回收站',exact=True)
    check('Enter on default confirmation keeps the note',target.evaluate('(node)=>node===document.activeElement'))
    check('safe confirmation does not trash records',page.evaluate("!JSON.parse(localStorage.getItem('luke-memo-workspace-v1')).memos.find(n=>n.title==='交互回归测试专用手记').deletedAt"))
    sheet.get_by_role('button',name='移动到笔记本',exact=True).click()
    check('move subsection announces its heading',sheet.locator('[data-memo-step-title]').evaluate('(node)=>node===document.activeElement'))
    page.keyboard.press('Escape')
    check('return restores the move action focus',sheet.get_by_role('button',name='移动到笔记本',exact=True).evaluate('(node)=>node===document.activeElement'))
    sheet.get_by_role('button',name='关闭',exact=True).click();sheet.wait_for(state='detached')
    check('closing memo actions restores their actual trigger',more.evaluate('(node)=>node===document.activeElement'))
    page.get_by_role('tab',name='回到身边',exact=True).click()
    check('opaque bottom navigation does not allocate backdrop blur',page.locator('.sidebar').evaluate('(node)=>getComputedStyle(node).backdropFilter')=='none')
    page.get_by_role('button',name='打开设置',exact=True).first.click()
    page.locator('.settings').wait_for()
    check('decorative particles pause while settings covers home',page.locator('.season-particles span').evaluate_all('(nodes)=>nodes.every(n=>getComputedStyle(n).animationPlayState===\'paused\')'))
    page.locator('.settings').get_by_role('button',name='关闭',exact=True).click();page.locator('.settings').wait_for(state='detached')
    page.emulate_media(reduced_motion='reduce')
