import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {emptyArchive,nextArchiveBatch,commitChapter,reconciledArchive,sourceFingerprint,recentWindow,retrieveArchive,parseArchive,memoryTerms,relevantExcerpt} from '../../lib/memory-archive.ts';
import {parseData,emptyMemory} from '../../lib/companion.ts';
import {finishStudy} from '../../lib/study.ts';
const at='2026-09-15T02:00:00.000Z';
const messages=Array.from({length:60},(_,i)=>({who:i%2?'luke':'me',text:i===0?'我喜欢茉莉花，约好周日去旧书店。':`第${i}条记录`,at}));
const data={name:'测试',since:'2024-01-01',messages,tasks:[],notes:[],checks:[],memory:{...emptyMemory,pinned:'不要叫我小朋友',summary:'旧摘要仍保留',through:8}};
function chapter(){const batch=nextArchiveBatch(messages,emptyArchive());return commitChapter(messages,{...emptyArchive(),enabled:true},batch,'用户喜欢茉莉花，周日去旧书店。',at);}
test('old backup round-trips without migration or archive side effects',()=>assert.deepEqual(parseData(JSON.stringify(data)),data));
test('automatic memory is enabled by default as requested',()=>assert.equal(emptyArchive().enabled,true));
test('automatic batch leaves recent 12 originals in place',()=>{const b=nextArchiveBatch(messages,emptyArchive());assert.ok(b.to<=messages.length-12);assert.ok(b.to-b.from<=32);assert.equal(messages.length,60);});
test('completed short chats are automatically processed without manual activation',()=>assert.equal(nextArchiveBatch(messages.slice(0,10),emptyArchive()).to,10));
test('manual and automatic extraction both preserve originals and cover completed pairs',()=>assert.equal(nextArchiveBatch(messages.slice(0,10),emptyArchive(),true).to,10));
test('disabling archive rejects an automatic commit',()=>{const b=nextArchiveBatch(messages,emptyArchive());assert.equal(commitChapter(messages,{...emptyArchive(),enabled:false},b,'记忆',at),null);});
test('a manual request can create a chapter without enabling background work',()=>{const b=nextArchiveBatch(messages,emptyArchive(),true);assert.equal(commitChapter(messages,{...emptyArchive(),enabled:false},b,'记忆',at,false).enabled,false);});
test('summary append does not alter raw records or pinned notes',()=>{const before=JSON.stringify(data),a=chapter();assert.equal(a.chapters.length,1);assert.equal(JSON.stringify(data),before);});
test('archive survives main-storage round-trip and full backup representation',()=>{const a=chapter(),result=parseData(JSON.stringify({...data,memoryArchive:a}));assert.deepEqual(result.memoryArchive,a);assert.equal(result.memory.pinned,data.memory.pinned);assert.deepEqual(result.messages,messages);});
test('duplicate completion cannot append twice',()=>{const a=chapter(),b=nextArchiveBatch(messages,emptyArchive());assert.equal(commitChapter(messages,a,b,'重复',at),null);});
test('edited source rejects an in-flight response',()=>{const b=nextArchiveBatch(messages,emptyArchive()),edited=messages.map((m,i)=>i?m:{...m,text:'新约定'});assert.equal(commitChapter(edited,{...emptyArchive(),enabled:true},b,'旧摘要',at),null);});
test('history edits invalidate affected summaries but retain original data',()=>{const a=chapter(),edited=messages.map((m,i)=>i?m:{...m,text:'不再喜欢茉莉'});assert.equal(reconciledArchive(edited,a).chapters.length,0);assert.equal(a.chapters.length,1);});
test('shortened history is readable and stale chapters are not recalled',()=>{const a=chapter(),short=messages.slice(0,4),d=parseData(JSON.stringify({...data,messages:short,memory:emptyMemory,memoryArchive:a}));assert.equal(d.memoryArchive.chapters.length,1);assert.equal(retrieveArchive(short,a).chapters.length,0);});
test('favorite toggles do not invalidate textual provenance',()=>assert.equal(sourceFingerprint(messages,0,20),sourceFingerprint(messages.map(m=>({...m,favorite:true})),0,20)));
for(const summary of ['', ' '.repeat(2),'长'.repeat(2401)])test('invalid summary is rejected without overwrite '+summary.length,()=>assert.throws(()=>commitChapter(messages,{...emptyArchive(),enabled:true},nextArchiveBatch(messages,emptyArchive()),summary,at)));
for(const a of [null,{}, {version:2,enabled:false,chapters:[]},{version:1,enabled:'yes',chapters:[]}])test('reject malformed archive '+JSON.stringify(a),()=>assert.throws(()=>parseArchive(a,60)));
test('Chinese overlapping terms find words at arbitrary offsets',()=>assert.ok(memoryTerms('你还记得茉莉花吗').includes('茉莉')));
test('old user messages can be recalled without any model-generated chapter',()=>{const m=[...messages,{who:'me',text:'茉莉花和旧书店的约定呢？'}];assert.match(JSON.stringify(retrieveArchive(m)),/周日去旧书店/);});
test('demo text is excluded from source extraction and old-message recall',()=>{const m=messages.map((v,i)=>i?v:{...v,source:'demo'});assert.ok(!nextArchiveBatch(m,emptyArchive()).records.some(v=>v.source==='demo'));assert.ok(!retrieveArchive([...m,{who:'me',text:'茉莉花'}]).snippets.some(v=>v.index===0));});
test('long-message matching keeps tail details visible',()=>{const t='前'.repeat(6000)+'茉莉花约定';assert.match(relevantExcerpt(t,memoryTerms('茉莉花')),/茉莉花约定/);});
test('recent context is bounded while latest long message is intact',()=>{const m=messages.map(v=>({...v,text:'字'.repeat(2000)}));const r=recentWindow(m);assert.ok(r.messages.length<=7);assert.equal(r.messages.at(-1),m.at(-1));});
test('summarizer input is bounded even for one very long original',()=>{const m=[{who:'me',text:'长'.repeat(20000)},...messages];const b=nextArchiveBatch(m,emptyArchive());assert.equal(b.records[0].text.length,12000);assert.equal(m[0].text.length,20000);});
test('timer completion is idempotent and independent of display frames',()=>{const start=Date.parse(at),d={...data,study:{subject:'数学',startedAt:start}};const saved=finishStudy(d,start,start+65000);assert.equal(saved.focusLog[0].minutes,65000/60000);assert.deepEqual(finishStudy({...d,...saved},start,start+66000),{});});
const read=p=>fs.readFileSync(new URL('../../'+p,import.meta.url),'utf8');
test('timer footer and browser-native date input are removed',()=>{assert.doesNotMatch(read('components/luke-companion.tsx'),/只为已结束并保存/);assert.doesNotMatch(read('components/timer-workspace.tsx'),/type="date"/);});
test('focus pendant animates only transform with reduced-motion handling',()=>{const css=read('components/timer-polish.css');assert.match(css,/@keyframes luke-focus-sway/);assert.match(css,/prefers-reduced-motion/);assert.doesNotMatch(css,/filter:|animation:.*background/);});
test('worker cancels model processing and bounds timeout',()=>{const s=read('hooks/use-conversation-memory.ts');assert.match(s,/60000/);assert.match(s,/latest.memoryArchive!==initialArchive/);assert.match(s,/controller.signal.aborted/);});
test('normal send does not wait for legacy rolling summaries',()=>assert.doesNotMatch(read('app/page.tsx'),/await prepareMemory/));
test('new version keeps the original upgrade identity',()=>{const s=read('mobile/android/AndroidManifest.xml');assert.match(s,/902010/);assert.match(s,/2\.0\.5/);assert.match(s,/com.luke.summer/);});
