"""Real note actions, long-press, geometry and persisted-data regression checks."""
def verify_memo_polish(page, check, out):
    page.set_viewport_size({'width':390,'height':844})
    page.emulate_media(reduced_motion='no-preference')
    page.get_by_role('tab',name='时光手记',exact=True).click()
    page.get_by_role('button',name='新建笔记',exact=True).click()
    page.get_by_label('笔记标题',exact=True).fill('和夏彦一起珍藏的小事')
    page.get_by_label('笔记正文',exact=True).fill('今天把搁置很久的计划推进了一点。\n不用着急，一页一页慢慢写。\n\n这是自动检查用的独立测试笔记，不是用户资料。')
    page.get_by_role('button',name='返回笔记列表',exact=True).click()
    page.locator('[data-memo-editor=true]').wait_for(state='detached')
    more=page.get_by_role('button',name='手记操作：和夏彦一起珍藏的小事',exact=True)
    more.wait_for()
    box=more.bounding_box()
    check('note always-visible more target is at least 44px',box['width']>=44 and box['height']>=44,box)
    page.screenshot(path=str(out/'notes-list.png'))
    more.click()
    sheet=page.locator('[data-memo-actions=true]');sheet.wait_for();page.wait_for_timeout(400)
    check('note actions do not open editor simultaneously',page.locator('[data-memo-editor=true]').count()==0)
    page.screenshot(path=str(out/'notes-actions.png'))
    for width,height in [(320,568),(390,844),(844,390),(768,1024)]:
        page.set_viewport_size({'width':width,'height':height});page.wait_for_timeout(200)
        rect=sheet.bounding_box();close=sheet.get_by_role('button',name='关闭',exact=True).bounding_box()
        check(f'note action sheet within viewport {width}x{height}',rect['x']>=-1 and rect['y']>=-1 and rect['x']+rect['width']<=width+1 and rect['y']+rect['height']<=height+1,rect)
        check(f'note action close stays reachable {width}x{height}',close['x']>=0 and close['y']>=0 and close['x']+close['width']<=width+1 and close['y']+close['height']<=height+1,close)
    page.set_viewport_size({'width':390,'height':844})
    sheet.get_by_role('button',name='移到回收站',exact=True).click()
    check('delete asks confirmation before altering records',page.evaluate("JSON.parse(localStorage.getItem('luke-memo-workspace-v1')).memos.find(n=>n.title==='和夏彦一起珍藏的小事').deletedAt") is None)
    sheet.get_by_role('button',name='保留手记',exact=True).click()
    sheet.get_by_role('button',name='置顶',exact=True).click();sheet.wait_for(state='detached')
    check('pin persists after animated sheet closes',page.evaluate("!!JSON.parse(localStorage.getItem('luke-memo-workspace-v1')).memos.find(n=>n.title==='和夏彦一起珍藏的小事').pinnedAt"))
    row=page.locator('[data-memo-id]').filter(has_text='和夏彦一起珍藏的小事')
    row.scroll_into_view_if_needed();page.wait_for_timeout(200)
    b=row.bounding_box();x=b['x']+35;y=b['y']+25
    client=page.context.new_cdp_session(page)
    client.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':[{'x':x,'y':y,'id':1}]})
    page.wait_for_timeout(600)
    client.send('Input.dispatchTouchEvent',{'type':'touchEnd','touchPoints':[]})
    sheet.wait_for();page.wait_for_timeout(300)
    check('trusted long press opens exactly one action sheet',sheet.count()==1 and page.locator('[data-memo-editor=true]').count()==0)
    sheet.get_by_role('button',name='关闭',exact=True).click();sheet.wait_for(state='detached')
    row.focus();row.press('Shift+F10');sheet.wait_for()
    check('keyboard can reach long-press actions',sheet.is_visible())
    sheet.get_by_role('button',name='选择多条手记',exact=True).click();sheet.wait_for(state='detached')
    check('multi-select starts with exactly the chosen note',page.locator('[data-memo-id][aria-pressed=true]').count()==1)
    page.get_by_role('button',name='退出多选',exact=True).click()
    row.click();page.get_by_label('笔记正文',exact=True).wait_for();page.wait_for_timeout(350)
    page.screenshot(path=str(out/'notes-editor.png'))
    check('editor preserves draft after context actions',page.get_by_label('笔记正文',exact=True).input_value().startswith('今天把搁置'))
    page.get_by_role('button',name='更多操作',exact=True).click();sheet.wait_for();page.wait_for_timeout(350)
    close=sheet.get_by_role('button',name='关闭',exact=True)
    check('actions remain clickable above editor',close.is_visible())
    close.click();sheet.wait_for(state='detached')
    check('closing actions preserves editor',page.get_by_label('笔记正文',exact=True).is_visible())
    page.get_by_role('button',name='返回笔记列表',exact=True).click();page.locator('[data-memo-editor=true]').wait_for(state='detached')
    page.emulate_media(reduced_motion='reduce')
    more.click();sheet.wait_for();sheet.get_by_role('button',name='关闭',exact=True).click();sheet.wait_for(state='detached')
    check('reduced-motion note sheet leaves no overlay',page.locator('[data-slot=dialog-overlay]').count()==0)
    client.detach()
