import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {emptyArchive,nextArchiveBatch,commitChapter,decodeExtraction,mergeFacts,editFact,forgetFact,retrieveArchive,sourceFingerprint} from '../../lib/memory-archive.ts';
import {parseDisplay,validAvatar,DEFAULT_DISPLAY} from '../../lib/display-preferences.ts';
import {normalizeMeteo,meteoURL,coordinates,isFresh} from '../../lib/weather.ts';
import {encodeSnapshot} from '../../lib/durable-store.ts';
import {chatContext} from '../../lib/model.ts';
const read=p=>readFileSync(new URL('../../'+p,import.meta.url),'utf8');
const at='2026-09-15T03:00:00.000Z';
const pair=[{who:'me',text:'我喜欢茉莉花。',at},{who:'luke',text:'那下次一起看看。',at}];
const batch=nextArchiveBatch(pair,emptyArchive());
const original=JSON.stringify(pair);
const f={key:'喜欢的花',value:'茉莉花',quote:'我喜欢茉莉花',sourceIndex:0,updatedAt:at};
const record=(facts)=>JSON.stringify({summary:'用户喜欢茉莉花。',facts});
const archived=()=>mergeFacts(commitChapter(pair,emptyArchive(),batch,'用户喜欢茉莉花。',at),[f]);
const data={name:'测试',since:'2024-01-01',messages:pair,tasks:[],notes:[],checks:[]};
test('single initial greeting is not sent to the summarizer',()=>assert.equal(nextArchiveBatch([pair[1]],emptyArchive()),null));
test('unanswered or interrupted last turn waits for completion',()=>{assert.equal(nextArchiveBatch([pair[0]],emptyArchive()),null);assert.equal(nextArchiveBatch([pair[0],{...pair[1],interrupted:true}],emptyArchive()),null);});
test('completed two-message chat is automatically eligible',()=>assert.equal(batch.to,2));
test('grounded extraction accepts an exact user quotation and stable key',()=>assert.deepEqual(decodeExtraction(record([f]),batch,at).facts,[f]));
for(const invalid of [{...f,sourceIndex:1,quote:'下次一起'}, {...f,quote:'我喜欢海棠'}, {...f,sourceIndex:99},{...f,quote:'我'}, {...f,value:''}])test('unverifiable model fact is not added '+JSON.stringify(invalid),()=>assert.equal(decodeExtraction(record([invalid]),batch,at).facts.length,0));
test('bad JSON does not overwrite existing memories',()=>{const a=archived(),before=JSON.stringify(a);assert.throws(()=>decodeExtraction('错误回复',batch,at));assert.equal(JSON.stringify(a),before);});
test('newer explicit fact replaces same key, not unrelated facts',()=>{let a=archived();a=mergeFacts(a,[{...f,key:'饮品',value:'茶'}]);const n=mergeFacts(a,[{...f,value:'海棠',sourceIndex:10}]);assert.equal(n.facts.find(x=>x.key===f.key).value,'海棠');assert.equal(n.facts.find(x=>x.key==='饮品').value,'茶');});
test('delayed extraction cannot regress a newer fact',()=>{const a=mergeFacts(archived(),[{...f,value:'海棠',sourceIndex:10}]);assert.equal(mergeFacts(a,[f]).facts[0].value,'海棠');});
test('manual correction remains locked against automatic rewriting',()=>{const a=editFact(archived(),f.key,'桂花');assert.equal(mergeFacts(a,[{...f,sourceIndex:20}]).facts[0].value,'桂花');assert.equal(a.facts[0].locked,true);});
test('forget tombstone prevents re-extraction and original-context leakage',()=>{const a=forgetFact(archived(),f.key,pair);const next=mergeFacts(a,[f]);assert.equal(next.facts.length,0);const recalled=retrieveArchive([...pair,{who:'me',text:'我喜欢什么花？'}],next);assert.doesNotMatch(JSON.stringify(recalled),/茉莉花/);assert.equal(JSON.stringify(pair),original);});
test('forgotten fact from an older chapter is excluded even after many later turns',()=>{const a=forgetFact(archived(),f.key,pair);const m=[...pair,...Array.from({length:100},(_,i)=>({who:i%2?'luke':'me',text:'新的日常'+i})),{who:'me',text:'以前喜欢的花？'}];assert.doesNotMatch(JSON.stringify(retrieveArchive(m,a)),/茉莉花/);});
test('fact ledger is actually supplied to ordinary chat prompts',()=>{const context=chatContext({...data,memoryArchive:archived()},'',new Date(at));assert.match(JSON.stringify(context),/rememberedFacts/);assert.match(JSON.stringify(context),/喜欢的花/);});
test('thousands of originals survive while model context is bounded',()=>{const messages=[...pair,...Array.from({length:5000},(_,i)=>({who:i%2?'luke':'me',text:'日常记录'+i}))];const before=sourceFingerprint(messages,0,messages.length),r=retrieveArchive(messages,archived());assert.ok(r.recent.messages.length<=24);assert.ok(r.snippets.length<=5);assert.equal(sourceFingerprint(messages,0,messages.length),before);assert.equal(messages.length,5002);});
test('immutable snapshot encoder matches JSON before and after edits',()=>{assert.equal(encodeSnapshot(data),JSON.stringify(data));const next={...data,draft:'新草稿',messages:[...pair,{who:'me',text:'新的内容'}]};assert.equal(encodeSnapshot(next),JSON.stringify(next));assert.equal(JSON.stringify(pair),original);});
test('global/chat preferences clamp independently and reject nonfinite input',()=>{const p=parseDisplay({scale:100,chatSize:2});assert.equal(p.scale,1.3);assert.equal(p.chatSize,13);assert.equal(parseDisplay({scale:NaN}).scale,1);assert.equal(parseDisplay({chatSize:Infinity}).chatSize,16);});
for(const value of ['javascript:alert(1)','https://example.com/avatar.svg','data:image/svg+xml;base64,PHN2Zz4=',null])test('avatar rejects unsafe or nonlocal content '+value,()=>assert.equal(validAvatar(value),false));
test('all six original supplied artworks are present in the built asset catalog',()=>{for(const f of ['companions/dog','companions/toast','companions/cat','chat-skins/tea','chat-skins/sunflower','chat-skins/hearts'])assert.ok(existsSync(new URL('../../public/images/'+f+'.webp',import.meta.url)));});
test('default user and character avatars are separate',()=>{assert.match(DEFAULT_DISPLAY.avatar,/dog/);assert.equal(DEFAULT_DISPLAY.lukeAvatar,'cat');});
const unix=Date.parse('2026-09-14T16:00:00Z')/1000;
const meteo=()=>({utc_offset_seconds:28800,current:{temperature_2m:27,weather_code:0,time:unix+3600},daily:{time:[unix,unix+86400],weather_code:[0,61],temperature_2m_max:[30,28]},hourly:{time:[unix+7200],precipitation_probability:[70]}});
test('Meteo daily epochs become local dates rather than previous UTC days',()=>assert.deepEqual(normalizeMeteo(meteo()).days.map(d=>d.date),['2026-09-15','2026-09-16']));
test('rain probability is an umbrella reminder, not invented official warning',()=>{const w=normalizeMeteo(meteo());assert.equal(w.rainSoon,true);assert.equal(w.alert,'');});
for(const c of [{}, {temperature_2m:900,weather_code:0,time:unix},{temperature_2m:20,weather_code:999,time:unix}])test('reject incomplete or invalid weather '+JSON.stringify(c),()=>assert.throws(()=>normalizeMeteo({...meteo(),current:c})));
test('weather URL is HTTPS Open-Meteo only and requests seven local dates',()=>{const u=new URL(meteoURL(39,116));assert.equal(u.host,'api.open-meteo.com');assert.equal(u.searchParams.get('forecast_days'),'7');assert.equal(u.searchParams.get('timezone'),'auto');});
for(const c of [['',''],['abc',110],[91,0],[1,181]])test('invalid coordinate pair '+c,()=>assert.throws(()=>coordinates(...c)));
test('stale weather is not shared as live context',()=>{const now=Date.now(),w={...normalizeMeteo(meteo()),observedAt:now,fetchedAt:now};assert.equal(isFresh(w,now),true);assert.equal(isFresh(w,now+16*60000),false);});
test('Caiyun network and settings paths have been removed',()=>{for(const p of ['lib/weather.ts','components/connection-settings.tsx','components/connections.tsx','app/api/weather/route.ts'])assert.doesNotMatch(read(p),/caiyun|彩云|api\.caiyun/i);});
test('settings header lives outside its content scrollport',()=>{const s=read('components/ui/dialog.tsx');assert.ok(s.indexOf('{fixedHeader}')<s.indexOf('data-slot="dialog-scroll-body"'));assert.match(read('app/page.tsx'),/fixedHeader=\{<SettingsHeader/);});
test('chat windows and search pagination do not delete original history',()=>{const s=read('app/page.tsx');assert.match(s,/visibleEnd-80/);assert.match(s,/后面的聊天/);assert.match(s,/继续查看结果/);assert.doesNotMatch(s,/messages:data.messages.slice\(0/);assert.match(s,/取消更正/);});
test('one explicit current version and increased Android version',()=>{assert.equal(JSON.parse(read('package.json')).version,'2.0.5');assert.match(read('mobile/android/AndroidManifest.xml'),/902010/);assert.match(read('lib/release-info.ts'),/release\/v2.0.5-complete/);});
test('dependency lock only changes root app version, not inherited dependency pins',()=>{const p=JSON.parse(read('package-lock.json'));assert.equal(p.packages[''].version,'2.0.5');assert.equal(p.packages['node_modules/hasown'].version,'2.0.4');assert.equal(p.packages['node_modules/inherits'].version,'2.0.4');});
