"""Real pointer, layout and modal-lock tests; browser bridge calls are mocked."""
def verify_seasonal_polish(page, check):
    page.emulate_media(reduced_motion='no-preference')
    page.set_viewport_size({'width':390,'height':844})
    page.get_by_role('tab',name='回到身边',exact=True).click()
    page.evaluate("""()=>{window.__feedback=[];window.__appearance=[];window.LukeAndroid={hapticEvent:k=>window.__feedback.push(k),feedbackEnabled:e=>{window.__feedbackEnabled=e},startupAppearance:(s,p)=>window.__appearance.push([s,p])};window.dispatchEvent(new Event('luke-feedback-change'));}""")
    page.get_by_role('button',name='打开设置',exact=True).first.click();page.locator('.settings').wait_for()
    check('one trusted settings click emits one press',page.evaluate("JSON.stringify(window.__feedback)==='[\"press\"]'"))
    page.wait_for_timeout(100);page.get_by_role('tab',name='四季与昼夜',exact=True).click()
    check('tab selection uses selection feedback',page.evaluate("window.__feedback.at(-1)==='selection'"))
    for label,season in [('春','spring'),('夏','summer'),('秋','autumn'),('冬','winter')]:
        page.get_by_role('button',name=label,exact=True).click();page.wait_for_timeout(180)
        check('appearance syncs native '+season,page.evaluate("s=>window.__appearance.at(-1)?.[0]===s",season))
    page.get_by_role('button',name='关闭触感',exact=True).click();page.evaluate('window.__feedback=[]')
    page.get_by_role('button',name='随日期',exact=True).click()
    check('disabled haptics stay silent on trusted input',page.evaluate('window.__feedback.length===0'))
    page.get_by_role('button',name='轻柔反馈',exact=True).click();page.wait_for_timeout(110)
    page.get_by_role('button',name='试试当前触感',exact=True).click()
    check('re-enabled preview uses one selection tick',page.evaluate("JSON.stringify(window.__feedback)==='[\"selection\"]'"))
    page.evaluate("window.__feedback=[];document.querySelector('.settings [data-slot=dialog-close]').click()")
    page.locator('.settings').wait_for(state='detached')
    check('programmatic close never vibrates',page.evaluate('window.__feedback.length===0'))
    page.evaluate("""()=>{window.__maxModals=0;window.__modalObserver=new MutationObserver(()=>{window.__maxModals=Math.max(window.__maxModals,document.querySelectorAll('[role=dialog]').length)});window.__modalObserver.observe(document.body,{subtree:true,childList:true});}""")
    for width,height,reduced in [(320,568,False),(844,390,False),(390,844,True)]:
        page.set_viewport_size({'width':width,'height':height});page.emulate_media(reduced_motion='reduce' if reduced else 'no-preference')
        page.get_by_role('button',name='打开设置',exact=True).first.click();page.locator('.settings').wait_for()
        page.get_by_role('tab',name='生日与纪念日',exact=True).click();page.get_by_role('button',name='看看生日祝福',exact=True).click()
        dialog=page.locator('.birthday-refined');dialog.wait_for();close=dialog.get_by_role('button',name='关闭',exact=True);box=close.bounding_box()
        check(f'birthday close visible {width}x{height} reduced={reduced}',box and box['width']>=44 and box['height']>=44 and box['x']>=0 and box['y']>=0 and box['x']+box['width']<=width+1 and box['y']+box['height']<=height+1,box)
        check('birthday has a single modal/focus owner',page.evaluate('window.__maxModals<=1'),page.evaluate('window.__maxModals'))
        check('birthday has only twelve finite decorations',page.evaluate("[...document.querySelectorAll('.birthday-confetti i')].length===12 && [...document.querySelectorAll('.birthday-confetti i')].every(n=>getComputedStyle(n).animationIterationCount!=='infinite')"))
        if reduced:check('birthday reduced motion has no running decoration',page.evaluate("document.getAnimations().filter(a=>a.playState==='running').length===0"))
        if height<480:
            page.evaluate("document.querySelector('.birthday-card').style.fontSize='24px';document.querySelector('.birthday-card h2').style.fontSize='40px'")
            dialog.get_by_role('button',name='收下这份祝福',exact=True).click()
        else:close.click()
        dialog.wait_for(state='detached');page.locator('.settings').wait_for()
        check('birthday preview does not mark the day as seen',page.evaluate("localStorage.getItem('luke-birthday-seen')===null"))
        page.locator('.settings').get_by_role('button',name='关闭',exact=True).click();page.locator('.settings').wait_for(state='detached')
        check('birthday returns without scroll-blocking overlay',page.locator('[data-slot=dialog-overlay]').count()==0)
    page.evaluate('window.__modalObserver.disconnect()')
    original=page.evaluate("localStorage.getItem('luke-companion-v1')")
    page.evaluate("""()=>{const d=JSON.parse(localStorage.getItem('luke-companion-v1'));const now=new Date();d.birthday=`2000-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;localStorage.setItem('luke-companion-v1',JSON.stringify(d));localStorage.removeItem('luke-birthday-seen');}""")
    page.reload();page.locator('.birthday-refined').wait_for()
    page.locator('.birthday-refined').get_by_role('button',name='先回到身边',exact=True).click();page.locator('.birthday-refined').wait_for(state='detached')
    check('automatic birthday acknowledgement persists',page.evaluate("!!localStorage.getItem('luke-birthday-seen')"))
    page.reload();page.get_by_role('button',name='打开设置',exact=True).first.wait_for();page.wait_for_timeout(550)
    check('acknowledged birthday does not recur after cold page reload',page.locator('.birthday-refined').count()==0)
    page.evaluate("raw=>localStorage.setItem('luke-companion-v1',raw)",original)
    page.reload();page.get_by_role('button',name='打开设置',exact=True).first.wait_for()
