import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {holidayFor,parseCalendarDate} from '../../lib/china-holidays.ts';
const read=p=>readFileSync(new URL('../../'+p,import.meta.url),'utf8');
test('2026 rest days and makeup days match the complete official schedule',()=>{let rest=0,work=0;for(let m=1;m<=12;m++)for(let d=1;d<=31;d++){const key=`2026-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`;if(!parseCalendarDate(key))continue;const h=holidayFor(key);if(h?.kind==='rest')rest++;if(h?.kind==='work')work++;}assert.equal(rest,33);assert.equal(work,6);});
test('national day makeup dates are not weekends off',()=>{for(const day of ['2026-09-20','2026-10-10'])assert.equal(holidayFor(day)?.kind,'work');});
test('spring festival has the published nine-day interval',()=>{for(let d=15;d<=23;d++)assert.equal(holidayFor(`2026-02-${d}`)?.name,'春节');assert.equal(holidayFor('2026-02-14')?.kind,'work');assert.equal(holidayFor('2026-02-28')?.kind,'work');});
test('uncollected years do not invent official calendars',()=>{assert.equal(holidayFor('2027-10-01'),null);assert.equal(holidayFor('2025-10-01'),null);});
test('date parser validates leap years and preserves local dates',()=>{assert.ok(parseCalendarDate('2000-02-29'));assert.equal(parseCalendarDate('2001-02-29'),null);assert.equal(parseCalendarDate('2026-04-31'),null);assert.equal(parseCalendarDate('1899-12-31'),null);assert.equal(parseCalendarDate('2101-01-01'),null);assert.equal(parseCalendarDate('2026-10-01').getDate(),1);});
test('date picker has explicit apply/cancel and no native date input',()=>{const s=read('components/date-field.tsx');assert.match(s,/确定日期/);assert.match(s,/取消/);assert.match(s,/disabled=\{!allowed\(draft\)\}/);assert.doesNotMatch(s,/type="date"/);});
test('settings separates model and weather forms',()=>{const s=read('app/page.tsx');assert.match(s,/<ModelSettings connections=/);assert.match(s,/<WeatherSettings connections=/);assert.match(s,/<SettingsNavigation /);});
test('navigation has labelled search and a nested back control',()=>{const s=read('components/settings-navigation.tsx');assert.match(s,/aria-label="搜索设置"/);assert.match(s,/aria-label="返回设置目录"/);assert.match(s,/aria-label=\{title\}/);});
test('calendar source is official and accessible in the UI',()=>{assert.match(read('components/plan-calendar.tsx'),/href=\{HOLIDAY_SOURCE\}/);assert.match(read('lib/china-holidays.ts'),/www.beijing.gov.cn/);});
test('version code advances without changing storage or main application package source',()=>{const s=read('mobile/android/AndroidManifest.xml');assert.match(s,/902007/);assert.match(s,/2.0.2/);assert.match(s,/com.luke.summer/);});
