"""Real bundle interaction, using isolated model responses rather than a live account."""
import json
from playwright.sync_api import expect, Error

def verify_timer_memory204(page, check, out):
    stored=page.evaluate('JSON.stringify({...localStorage})')
    page.set_viewport_size({'width':390,'height':844})
    def nav(name):page.get_by_role('tab',name=name,exact=True).click()
    def settings():
        nav('回到身边');page.get_by_role('button',name='打开设置',exact=True).first.click()
        page.get_by_label('搜索设置',exact=True).wait_for()
    def close():
        page.locator('.settings').get_by_role('button',name='关闭',exact=True).click()
        page.locator('.settings').wait_for(state='detached')
    try:
        page.emulate_media(reduced_motion='no-preference')
        settings();page.get_by_role('tab',name='四季与昼夜',exact=True).click()
        page.get_by_role('switch',name='季节动画',exact=True).check();close()
        nav('计时')
        end=page.get_by_role('button',name='结束并保存',exact=True)
        if end.is_visible():end.click()
        pendant=page.locator('.focus-keepsake-pendant')
        check('timer has no repeated footer guidance',page.get_by_text('只为已结束并保存的学习记录盖印；进行中的计时不提前计入。',exact=True).count()==0)
        check('timer pendant starts paused',pendant.evaluate('(e)=>getComputedStyle(e).animationPlayState')=='paused')
        page.get_by_role('button',name='开始计时',exact=True).click()
        page.locator('.focus-keepsake').scroll_into_view_if_needed();page.wait_for_timeout(400)
        frames=page.evaluate('''()=>new Promise(resolve=>{const a=[],start=performance.now(),node=document.querySelector('.focus-keepsake-pendant');function step(){a.push({t:performance.now()-start,transform:getComputedStyle(node).transform});if(performance.now()-start<750)requestAnimationFrame(step);else resolve(a);}requestAnimationFrame(step);})''')
        (out/'timer-keepsake-frames.json').write_text(json.dumps(frames))
        check('timer keepsake image is decoded',pendant.locator('img').evaluate('(e)=>e.complete && e.naturalWidth>0'))
        check('running timer has actual intermediate pendant frames',len(set(f['transform'] for f in frames))>=5,frames[:5])
        before=page.locator('[role=timer]').inner_text();page.wait_for_timeout(1300)
        check('display clock advances independently',page.locator('[role=timer]').inner_text()!=before)
        page.screenshot(path=str(out/'timer-keepsake.png'))
        nav('回到身边');nav('计时')
        check('changing page preserves the active study',page.get_by_role('button',name='结束并保存',exact=True).is_visible())
        page.emulate_media(reduced_motion='reduce')
        check('reduced motion disables only decoration',pendant.evaluate('(e)=>getComputedStyle(e).animationName')=='none')
        page.get_by_role('button',name='结束并保存',exact=True).click()
        check('ending study returns the pendant to still state',page.locator('.focus-keepsake').get_attribute('data-playing')=='false')
        page.get_by_role('button',name='学习统计日期',exact=True).click()
        page.get_by_label('输入指定日期',exact=True).fill('20261001')
        page.get_by_role('button',name='确定日期',exact=True).click()
        check('timer statistics uses themed date selection', '2026 / 10 / 01' in page.get_by_role('button',name='学习统计日期',exact=True).inner_text())
        palettes=[]
        for season in ['春','夏','秋','冬']:
            settings();page.get_by_role('tab',name='四季与昼夜',exact=True).click()
            page.get_by_role('button',name=season,exact=True).click();close();nav('计时');page.wait_for_timeout(850)
            colors=page.locator('.luke-study-dial').evaluate('(e)=>({fg:getComputedStyle(e).color,bg:getComputedStyle(e).backgroundColor,key:getComputedStyle(e.querySelector(".focus-keepsake svg")).color})')
            palettes.append(colors)
        check('four seasonal timer accents are distinct',len(set(p['key'] for p in palettes))==4,palettes)
        # Load synthetic history before React mounts, respecting the storage-conflict guard.
        page.evaluate('''()=>{const d=JSON.parse(localStorage.getItem('luke-companion-v1'));d.messages=Array.from({length:60},(_,i)=>({who:i%2?'luke':'me',text:i===0?'我喜欢茉莉花，约好周日去旧书店。':'章节测试记录 '+i,at:new Date().toISOString()}));d.draft='';d.memory={summary:'旧摘要保留',through:8,pinned:'固定约定保留',updatedAt:''};delete d.memoryArchive;localStorage.setItem('luke-companion-v1',JSON.stringify(d));}''')
        page.reload();page.get_by_role('tab',name='回到身边',exact=True).wait_for()
        settings();page.get_by_role('tab',name='长期聊天记忆',exact=True).click()
        switch=page.get_by_role('switch',name='自动整理长期记忆',exact=True)
        check('memory auto requests require opt-in',not switch.is_checked())
        check('existing pinned memory is retained',page.get_by_label('希望他牢牢记住的事',exact=True).input_value()=='固定约定保留')
        page.get_by_role('button',name='返回设置目录',exact=True).click();page.get_by_role('tab',name='聊天模型',exact=True).click()
        page.get_by_label('模型接口地址',exact=True).fill('https://memory-fixture.invalid/v1')
        page.get_by_label('模型名称',exact=True).fill('isolated-test-model')
        page.get_by_label('模型密钥',exact=True).fill('not-a-real-key')
        requests=[];summary=['长'*2500];hold=[False];deferred=[]
        def model_reply(route):
            payload=route.request.post_data_json;requests.append(payload)
            if hold[0] and not payload.get('stream'):
                deferred.append(route);return
            text='记得：旧书店和茉莉花，这是测试回复。' if payload.get('stream') else summary[0]
            route.fulfill(status=200,content_type='application/json',body=json.dumps({'choices':[{'message':{'content':text},'finish_reason':'stop'}]},ensure_ascii=False))
        page.route('https://memory-fixture.invalid/**',model_reply)
        page.get_by_role('button',name='保存模型设置',exact=True).click()
        page.get_by_role('button',name='返回设置目录',exact=True).click();page.get_by_role('tab',name='长期聊天记忆',exact=True).click()
        page.get_by_role('button',name='整理下一章节',exact=True).click()
        expect(page.get_by_text('记忆整理结果过长或为空，原有章节未覆盖。',exact=True)).to_be_visible()
        check('invalid model summary stays a recoverable error',page.locator('.memory-chapters details').count()==0)
        summary[0]='用户说喜欢茉莉花，周日想去旧书店。此为测试整理。'
        page.get_by_role('button',name='整理下一章节',exact=True).click()
        expect(page.locator('.memory-chapters details')).to_have_count(1,timeout=10000)
        d=page.evaluate("JSON.parse(localStorage.getItem('luke-companion-v1'))")
        check('manual summary appends a chapter without deleting messages',len(d['messages'])==60 and len(d['memoryArchive']['chapters'])==1)
        check('manual summary does not implicitly enable automatic requests',not d['memoryArchive']['enabled'])
        check('old summary and pinned facts survive chapter creation',d['memory']['summary']=='旧摘要保留' and d['memory']['pinned']=='固定约定保留')
        page.locator('.memory-chapters summary').first.click()
        check('chapter exposes corresponding original source',page.get_by_role('button',name='查看对应原文',exact=True).is_visible())
        page.get_by_label('搜索聊天记忆章节',exact=True).fill('找不到的内容')
        check('chapter search handles empty result',page.get_by_text('没有匹配的章节。',exact=True).is_visible())
        page.get_by_label('搜索聊天记忆章节',exact=True).fill('')
        switch.check()
        expect(page.locator('.memory-chapters details')).to_have_count(2,timeout=70000)
        check('idle opted-in worker updates chapters automatically',page.evaluate("JSON.parse(localStorage.getItem('luke-companion-v1')).memoryArchive.chapters.length")==2)
        switch.uncheck();page.screenshot(path=str(out/'conversation-memory.png'))
        d=page.evaluate("JSON.parse(localStorage.getItem('luke-companion-v1'))")
        check('chapter source coverage advances without replacing first chapter',d['memoryArchive']['chapters'][0]['from']==0 and d['memoryArchive']['chapters'][1]['from']==d['memoryArchive']['chapters'][0]['to'])
        hold[0]=True
        before_cancel=page.evaluate("JSON.parse(localStorage.getItem('luke-companion-v1')).memoryArchive.chapters")
        page.get_by_role('button',name='整理下一章节',exact=True).click()
        expect(page.get_by_role('button',name='取消整理',exact=True)).to_be_visible()
        for _ in range(100):
            if deferred:break
            page.wait_for_timeout(50)
        check('memory cancellation covers an actual pending model request',len(deferred)==1)
        page.get_by_role('button',name='取消整理',exact=True).click()
        expect(page.get_by_role('button',name='整理下一章节',exact=True)).to_be_visible()
        try:deferred.pop().fulfill(status=200,content_type='application/json',body=json.dumps({'choices':[{'message':{'content':'这是取消后到达的结果，不应写入。'},'finish_reason':'stop'}]},ensure_ascii=False))
        except Error:pass  # Aborted browser requests may no longer accept a response.
        hold[0]=False;page.wait_for_timeout(400)
        check('cancelled memory result cannot append or replace chapters',page.evaluate("JSON.parse(localStorage.getItem('luke-companion-v1')).memoryArchive.chapters")==before_cancel)
        close();nav('悄悄话')
        page.get_by_role('textbox',name='发送给夏彦的消息',exact=True).fill('茉莉花和旧书店的约定呢？')
        page.get_by_role('button',name='发送消息',exact=True).click()
        expect(page.get_by_text('记得：旧书店和茉莉花，这是测试回复。',exact=True)).to_be_visible(timeout=10000)
        outgoing=next(r for r in reversed(requests) if r.get('stream'))
        payload='\n'.join(m['content'] for m in outgoing['messages'])
        check('normal reply receives relevant older original and chapter context',all(term in payload for term in ['relevantOriginalMessages','memoryChapters','我喜欢茉莉花，约好周日去旧书店。','固定约定保留']))
        page.reload();settings();page.get_by_role('tab',name='长期聊天记忆',exact=True).click()
        check('chapters survive an application reload',page.locator('.memory-chapters details').count()==2)
        close()
    finally:
        page.evaluate('''raw=>{localStorage.clear();for(const [key,value] of Object.entries(JSON.parse(raw)))localStorage.setItem(key,value);}''',stored)
        page.reload();page.get_by_role('tab',name='回到身边',exact=True).wait_for()
